[#4] 회원가입 기능 구현
f-lab-edu/DoorRush pull request #30
Opened 2021-11-20 19:11 UTC by yeoonjae

# Pull Request

## 종류

- [ ] Code Review 반영 
- [x] New Feature 
- [ ] Bug Fix
- [ ] CI / CD
- [ ] setup

## 회원가입 기능 구현

- 회원가입 MVC와 Test 코드 작성
- property -> yaml 파일로 변경

2021-11-22 15:52 UTC, f-lab-jd requested changes
@yeoonjae 
고생하셨습니다~! 👍 
많은 리뷰를 드리게 되었는데요. ㅎㅎ 관련해서 한번 살펴봐주시고, 
이해가 안되거나 어려운 부분이 있다면 편히 말씀해주세요~!

2021-11-22 15:52 UTC, f-lab-jd commented on build.gradle
> +    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.0'
@yeoonjae @ypr821 
라이브러리 중에 `spring-boot-starter-ooo`를 많이 보셨을텐데요.
`starter` 는 무엇을 해주는걸까요?
바로 아래 라인에 있는 junit 도 starter 에서 제공받을 수 있을까요?

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    @PostMapping("/join")
@yeoonjae 
Restful 하게 설계하신걸까요...?ㅎㅎ 
다시 한번 고민해보심 좋을 것 같습니다.

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    // 회원가입 메소드
@yeoonjae 
해당 주석을 남겨야하는 목적이 있을까요~? 
`메소드명과 메소드의 파라미터, 메소드의 리턴타입` 만으로 유추할 수 있지 않을까요? 

주석은 어떤 경우에 남기는게 좋을까요?
(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    public ResponseEntity joinUser(@RequestBody UserDto userDto) throws Exception {
@yeoonjae 

1. ResponseEntity 는 바디 타입에 대한 파라미터가 함께 사용되어야하지 않을까요~?
2. 회원가입을 하게 되는 Restful API 인데, 응답 파라미터가 없어도 될까요?
3. `throws Exception` 이 의미하는것은 무엇일까요? 


(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +        boolean checkId = userService.getUserById(userDto.getUserId());
@yeoonjae 
`checkId`  네이밍은 동사형인데요.  `boolean` 타입과는 어떤 네이밍이 어울릴까요~? 

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +        if (checkId) {
@yeoonjae 
`Controller` 보다는 `Service` 레이어에 더 어울리는 로직이 아닐까요? 
레이어드 아키택쳐에서 각 레이어의 역할은 무엇일까요? 
(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +            throw new Exception("아이디가 존재합니다.");
@yeoonjae
체크드 익셉션과 언체크드 익셉션의 차이는 무엇일까요~?
정말 정말 중요한 개념인데요. 토비의 스프링 Chapter 4 를 참고하시면 좋을 것 같습니다.
여기에서 Exception 을 던지고... 이 메소드에서 `throws Exception` 을 한다면, 예외 처리는 어디서해야할까요?

 (cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +    void joinUser(UserDto userDto);
@yeoonjae 
`join` 은 회원가입시 서비스에서 사용이되는 용어라고 생각하였는데요.
`Mapper` 입장에서도 `join` 이 맞을까요~? 
그리고 데이터를 삽입한 결과를 리턴하는 것은 어떨까요~?

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +    Optional<UserDto> getUserById(String id);
@yeoonjae 
Controller, Service, Mapper 모두 `UserDTO` 라는 클래스 한가지를 사용하였는데요.
DTO 클래스의 목적은 무엇일까요? 그리그 DTO 클래스를 어느 레이어까지 적용하는게 적합까요?

리턴타입으로 `Optional` 은 잘 활용하셨습니다. 👍 

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/UserDto.java
> +    private String userDefaultAddr;
@yeoonjae 
`Address` 를 `Addr` 로 줄이는 이유가 있으신가요~? 
프로젝트 컨벤션을 한번 더 확인해보심 좋을 것 같습니다. ㅎㅎ
https://github.com/f-lab-edu/DoorRush/wiki/3.-Project-Convention

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/UserDto.java
> +@Builder
@yeoonjae 
java 개발시 `lombok` 은 보일러플레이트코드를 쉽게 만들어주는 정말 유용한 라이브러리인데요.
관습적으로 사용하다보면, 그 의미를 잘 모르고 사용할때도 생길 것 같습니다. 
프로젝트에 처음 사용되는 어노테이션이라면 저희 컨벤션에 명시한것처럼 그 의미를 주석으로 가독성있게 적어주셔도 좋을 것 같습니다.

1. `@NoArgsConstructor` 가 현재 클래스에 필요한 이유가 무엇인가요?
2. https://github.com/f-lab-edu/DoorRush/pull/30/files#diff-27c27aef4362993c4ed401e73fe864283e2db11514b3109e92e88cd3c74aa99bR18 생성자 주입부분은 lombok 으로 해결 할 수 있는 방법은 없을까요?
3. `@Builder` 어노테이션을 활용해서 외부에서도 빌더패턴으로 객체를 생성할 수 있는데 https://github.com/f-lab-edu/DoorRush/pull/30/files#diff-d90a781629126f40abb8d2d55ef29e2706e06e3fab9d5f8471c116c6da578764R19 생성자는 왜 필요할까요~? 

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/UserDto.java
> +    public UserDto(String userId, String password, String userName, String userPhoneNumber,
@yeoonjae 
생성자가 아니라 가독성있게 팩토리 패턴을 이용해서 객체를 생성하는것은 어떨까요?

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/UserDto.java
> +    private String userDefaultAddr;
@yeoonjae 
앞에 `user` 라는 접두사가 꼭 필요할까요? (DB 컬럼도 마찬가지 입니다)
꼭 필요하다면, password 도 일관성있게 `userPassword` 라고 네이밍해야하지 않을까요~?

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +public interface UserService {
@yeoonjae 
`UserService` 인터페이스가 필요한 이유가 있으신가요~? 

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserServiceImpl.java
> +    // 회원 insert
@yeoonjae 
메소드마다 주석이 꼭 필요할지, 주석 관련해서 어떠한 일관성 있는 규칙을 가져갈지 다시 고민해보시면 좋을 것 같습니다.
(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserServiceImpl.java
> +    public boolean getUserById(String userId) throws Exception {
@yeoonjae 
1. `throws Exception` 을 해야하는 이유가 있을까요? 

2. `getUserById` 메소드만 보면 id 중복확인 결과 boolean 을 리턴하기보다 사용자정보를 리턴할거로 기대가 되는데요. `boolean` 과 어울리는 메소드명으로 수정해주시면 좋을 것 같습니다.

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserServiceImpl.java
> +        boolean checkId = false;
@yeoonjae 
`UserController` 에서 드린 의견과 같습니다.

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserServiceImpl.java
> +        }else{ // 존재하지 않으면
@yeoonjae 포맷터가 올바르게 적용되지 않은 것 같습니다.

@yeoonjae @ypr821 
저희 코드스타일 (포맷터) 관련 코드 컨벤션을 추가한 후, 포맷팅 설정을 할 수 있는 파일도 함께 업로드되면 좋을 것 같습니다.

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserServiceImpl.java
> +        if (! userDto.isEmpty()) { // 아이디가 존재하면
@yeoonjae 
1. `userDto.isPresent()` 를 사용하면 더 가독성이 좋을 것 같습니다.
2. 주석관련하여서는 전체적으로 한번 더 확인해주심 더 좋을 것 같습니다.

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/resources/application.yml
> +  jpa:
@yeoonjae 현재 저희 프로젝트에 필요한 설정일까요~?

(cc. @ypr821)

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/resources/application.yml
> +#properties 보다 가독성이 좋다.
@yeoonjae 
yml 안에서 주석처리할때, 띄어쓰기도 일관성을 지켜주시면 가독성에 더 좋을 것 같습니다.
`# abc` 
`#abc`

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/resources/application.yml
> +      mode: always
@yeoonjae 
👍 이 설정을 한 경우에 어떤 순서로 초기화를 진행할까요?

(cc. @ypr821)

2021-11-22 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +@Controller
@yeoonjae 
`@RestController` 가 아니어도 괜찮을까요? 
`@RestController` 와 `@Controller` 의 차이점에 대해 알고 계신가요~?

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/api/UserControllerTest.java
> +@WebMvcTest
@yeoonjae  👍 
테스트시 상태검증과 행위 검증에 대해 이해하고 계신가요~? 
한번 알아보셔도 좋을 것 같습니다. ㅎㅎ

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/api/UserControllerTest.java
> +            .andDo(print());
@yeoonjae 
`print()` 하는것만으로 올바르게 테스트가 될까요~?

(cc. @ypr821 )

2021-11-22 15:52 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/dao/UserMapperTest.java
> +        if(originUser.isEmpty()){
@yeoonjae 
프로젝트 전체적으로 포맷팅 관련해서 다시한번 확인해주심 좋을 것 같습니다.

(cc. @ypr821)

2021-11-22 15:52 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/dao/UserMapperTest.java
> +            userMapper.joinUser(user);
@yeoonjae 
mapper 에 대해 정확하게 테스트가 잘 되고 있는것일까요~?
Given, When, Then 구조로 (주석을 포함하여) 테스트를 만들어보시는것은 어떨까요? 
(https://github.com/f-lab-edu/DoorRush/pull/30/files#diff-21411e791bdce0ab550027ea3ccdebfda8ff63c36aed131baee6fb0ebdc60005R9 에서 잘 해주셨습니다) 

(cc. @ypr821 )

2021-11-22 16:53 UTC, ypr821 commented on build.gradle
> +    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.0'
spring-boot-starter는 아주 많은 것들을 자동으로 설정해주고 의존성을 가져오는 것 같습니다. 
autoconfigure도 보이고 stater-web은 웹에 관한 톰캣부터 json 등등 자동설정을 해주네요
그리고 stater-test하위에 junit도 보입니다!!

2021-11-22 16:54 UTC, ypr821 commented
@yeoonjae 님 고생하셨습니다 !!!!

2021-11-22 17:26 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +@Controller
@f-lab-jd 
'@RestController'를 사용하여 Restful한 웹서비스로 구현해야 할 것 같습니다. 수정하겠습니다! 

`@RestController`는 해당 '@responsebody' + `@Controller`  로 내부에 있는 모든 메소드가 '@responsebody'가 붙은 형태로 만들어주는 어노테이션입니다. 

'@Controller'는 ModelAndView를 반환하고, `@RestController`는 객체를 반환합니다.

2021-11-22 17:26 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +        boolean checkId = userService.getUserById(userDto.getUserId());
@f-lab-jd  검색으로 알아본 결과  `boolean` 타입은 앞에 prefix로 be동사인 `is` 또는 'has',`can`,`should`를 붙이는 것이 의도를 파악하기에 좋습니다. 또한 부정형을 사용하지 않는 것이 좋습니다. 중복을 체크하는 기능이니 변수명을 `isDuplicate` 로 변경하겠습니다! 

bool Type 변수명 
* is + 명사 
* is + 현재진행(~ing)
* is + 형용사
* 조동사 + 동사원형..

2021-11-22 17:42 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +        if (checkId) {
넵 Service에서 처리했어야 하는 로직인 것 같습니다..!! 레이어의 역할을 고려하여 구현하는 것에 더욱 신경쓰도록 하겠습니다!

* Controller : 요청을 받고 응답합니다. 
* Service : 비즈니스 로직을 담당합니다. 핵심 업무 로직 구현을 하며, Controller와 DAO 사이의 다리역할을 합니다. 
* Data Access Layer (DAO) : 데이터베이스 관련 로직을 처리합니다. 주로 데이터의 CRUD 연산을 수행하고, 가져온 관계형 정보를 저장하고 객체화 합니다.

2021-11-23 00:37 UTC, yeoonjae commented on build.gradle
> +    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.0'
`starter`는 spring-boot 애플리케이션 시작시에 포함할 수 있는 의존성 집합입니다. `starter` 는 프로젝트를 빠르게 시작하고 실행하는 데 필요한 의존성이 포함되어있습니다. 

 AspectJ를 사용하고 싶다면 `spring-boot-starter-aop`을 추가하고 `spring-boot-starter-test`를 추가하면 `junit`외에도 `Mockito` 등과 같은 테스트를 위한 스타터를 지원합니다. 

아래라인에 junit 추가한 것을 `spring-boot-starter-test`으로 변경하면 더 많은 테스트 기능을 사용할 수 있을 것 같습니다!

2021-11-23 11:39 UTC, f-lab-jd commented on build.gradle
> +    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.0'
@yeoonjae @ypr821  
두분 모두 잘 답변해주셨습니다~ `spring-boot-starter-test` 를 의존하시면 junit 을 비롯하여 테스트작성에 필요한 라이브러리들을 함께 의존할 수 있고) 스프링 부트 버전과 최적화된 라이브러리의 버전을 사용할 수 있어서 starter 를 사용하는게 더 좋아보입니다.

2021-12-03 06:49 UTC, yeoonjae commented
@f-lab-jd @ypr821 
안녕하세요 멘토님! 푸름님!

리뷰내용 반영하여 커밋했습니다.

gradle에 수정이 필요한 부분은 JaCoCo를 연동하면서 수정 진행하였습니다. 
그 외에 UserDto 클래스에 팩토리패턴을 적용하는 것은 이해가 조금 더 필요하여 issue 등록한 후 추후 반영하도록 하겠습니다!

2021-12-04 02:31 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +    int getCountId(String id);
@yeoonjae 
`getCount` 의 경우에는 `byId` 가 빠져있네요 ㅎㅎ 
id 파라미터의 경우에는 생략하는 경우도 있는데요.  중요한건 `일관성` 입니다. 

1. id 로만 조회하는 경우 `ById` 를 생략한다. 그 이외에는 2번과 같다.
2. 모든 조회의 경우, 조회 조건에 대해 `ByOOOAndOOOAnd ...` 를 붙여준다. 

위 두개 중 하나로 일관성있게 작성하시면 좋을 것 같습니다. (@ypr821)

2021-12-04 02:33 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/User.java
> +    public UserDto toUserDto(User user) {
@yeoonjae 
작성하신 코드처럼 `User` 도메인이 `UserDto` 를 의존하는게 더 좋을까요? 
아니면 `UserDto` 가 `User` 를 의존하는게 좋을까요? 
한번 고민해보시고, 답변을 남겨주시거나 멘토링시간에 함께 이야기를 나누어보면 좋을 것 같습니다. ㅎㅎ
(cc. @ypr821 )

2021-12-04 02:36 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/User.java
> +import javax.validation.constraints.NotNull;
@yeoonjae 
사용하지 않는 import 문은 수시로 제거해주는게 좋습니다.  보통 IDE 의 reformat 기능을 이용해서 제거하는데요. 
커밋하기전에 한번씩 하는 습관을 들여주시면 좋습니다! 
만약 이게 귀찮고 어려우시다면,  `git-hook` 을 이용하거나 `gradle 플러그인`을 이용해  커밋하기전에 진행하도록 하는 방법이 있습니다. 궁금하시다면 한번 찾아보셔도 좋을 것 같고, 찾아봤는데 적용이 어려우시다면 저에게 말씀해주세요~!
(cc. @ypr821 )

2021-12-04 02:39 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/User.java
> +    private String defaultAddress;
@yeoonjae 
예전에 멘토링시간에 함께 나누었던 내용인데요. ㅎㅎ 
`User` 에게 `defaultAddress` 라는 필드가 꼭 필요할까요? 

(cc. @ypr821 )

2021-12-04 02:41 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/User.java
> +    public UserDto toUserDto(User user) {
@yeoonjae 
코드를 더 보다보니 `UserDto` 도 `User` 를 의존하는것을 보았는데요. 
요청해 사용했던 UserDto 를 응답에도 사용하는게 아니라 별도로 새로 생성하는것은 어떨까요~? 

(cc. @ypr821 )

2021-12-04 02:42 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/UserDto.java
> +    public UserDto(UserDto userDto) {
@yeoonjae 
UserDto 를 받아서 새로운 UserDto 를 생성하는..? 요 메소드는 목적이 무엇인가요? ㅎㅎ

(cc. @ypr821 )

2021-12-04 02:42 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/exception/DuplicateUserIdException.java
> +public class DuplicateUserIdException extends RuntimeException {
👍

2021-12-04 02:46 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/exception/DuplicateUserIdException.java
> +    public DuplicateUserIdException(String message, Throwable cause) {
@yeoonjae 
현재 사용하지 않는 코드는 쿨하게 지워주는 습관을 들이시는게 좋습니다. ㅎㅎ
나중에 (가까운 시일내에) 꼭 필요한 코드라면 주석과 함께 그 사유를 구체적으로 남겨주시면 더 좋을 것 같습니다.

(cc. @ypr821 )

2021-12-04 02:46 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/exception/UserNotFoundException.java
> +    public UserNotFoundException(String message, Throwable cause) {
@yeoonjae 
위에 드린 리뷰와 같은 내용입니다~

(cc. @ypr821 )

2021-12-04 02:49 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    public void joinUser(User user) {
@yeoonjae 
`joinUser` 메소드에 대해 오버로딩을 사용하셨는데요. 이유가 있을까요~? 

(cc. @ypr821 )

2021-12-04 02:50 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +            throw new DuplicateUserIdException("회원가입이 실패하였습니다.");
@yeoonjae 
ID가 중복된 경우 위에서 처리해주었는데요. ㅎㅎ 
어떤 경우 실패할까요~? 


(cc. @ypr821 )

2021-12-04 02:52 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/dao/UserMapperTest.java
> +        User user = new User(userId, password, name, phoneNo, defaultAddress, email);
@yeoonjae 
User 객체에 `@Builder` 를 선언해두었는데, 생성자를 사용하신 이유가 있을까요? ㅎㅎ 

(cc. @ypr821 )

2021-12-04 02:54 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/dao/UserMapperTest.java
> +            System.out.println("not found");
@yeoonjae 
User 가 존재하지 않는 경우 로그가 아니라 빨간불이 떠야하지 않을까요~? ㅎㅎ

(cc. @ypr821 )

2021-12-04 02:57 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/dto/UserDtoTest.java
> +    public void userDto_builder_test() {
@yeoonjae 
요 테스트는 실행이 안되지 않나요..? ㅎㅎ 혹시 이유를 아실까요~? 
그리고 테스트 코드의 클래스도 `가독성` 과 `일관성` 이 중요합니다. 
현재 메소드는 카멜케이스와 스네이크 케이스가 혼용되어있는데, 다른 테스트클래스 메소드와 함께 일관성있게 작성해주시면 좋을 것 같습니다~

(cc. @ypr821 )

2021-12-04 03:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    @PostMapping("")
@yeoonjae 
(지극히 저의 개취 의견이니 참고만해주세요~! ㅎㅎ)  
RequestMapping 시 앞에 슬래시를 붙이는것은 어떤가요~? 
슬래시를 붙여주지 않더라도, RequestMapping 시 URL 젤 앞에 슬래시(`/`) 가 없는 경우, 스프링 `DefaultAnnotationHandlerMapping` 에서 자동으로 슬래시를 붙여주는데요. 
ㅎㅎ 모든 매핑 URL 마다 `"/"` 을 일관성있게 붙여주는게 저의 개취라서 소소하게 의견드립니다. 

(cc. @ypr821 )

2021-12-04 03:11 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    public ResponseEntity<UserDto> joinUser(@RequestBody UserDto userDto) {
@yeoonjae 

https://github.com/f-lab-edu/DoorRush/pull/30#discussion_r762375100 내용과 같은 내용리뷰입니다~
(cc. @ypr821 )

2021-12-04 03:13 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/api/UserControllerTest.java
> +        mockMvc.perform(post("/users")
@yeoonjae 👍 

(cc. @ypr821 )

2021-12-04 08:23 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +    int getCountId(String id);
by 붙이는 걸로 정하면 어떨까요?? @yeoonjae 님?

2021-12-04 08:59 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/domain/User.java
> +    public UserDto toUserDto(User user) {
@f-lab-jd  
User 도메인은 DB테이블과 바로 연결되므로 고정적이어야 하지만  UserDto는 View layer에서 자주 수정되거나  User 도메인이 확장된 클래스이기 때문에  UserDto가 User도메인에 의존할 수 있으나 반대의  의존관계는 생기지 않도록 해야할 거 같습니다. OCP !! OCP 맞나요,,? ㅎㅎ

2021-12-04 09:06 UTC, ypr821 commented
연재님 고생많으셨어요 덕분에 공부가 정말 많이 됩니다!!! 감사합니다!!! 화이팅

2021-12-04 13:20 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/User.java
> +    public UserDto toUserDto(User user) {
> User 도메인은 DB테이블과 바로 연결되므로 고정적이어야 합니다. 하지만 UserDto는 View layer에서 자주 수정되거나 User 도메인이 확장된 클래스이기 때문에 UserDto가 User도메인에 의존할 수 있으나 반대의 의존관계는 생기지 않도록 해야할 거 같습니다. 


@ypr821  토시하나 빠지지 않고 `완벽` 합니다. 👍 👍 
하지만 OCP 의 예시가 되는 케이스는 아닙니다..ㅎㅎ

2021-12-04 14:14 UTC, f-lab-jd approved these changes
고생 많으셨습니다. 👍

2021-12-04 14:19 UTC, ypr821 approved these changes
드디어!!!!!!!! 연재님 고생하셨습니다 박수!!!!!!

2021-12-04 14:19 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +            throw new Exception("아이디가 존재합니다.");
**체크드 익셉션**은  throws를 사용하거나 catch블록을 사용해서 반드시 Exception처리해야 합니다. 하지않으면 컴파일 에러가 발생합니다. 예) SQLException....

**언체크드 익셉션**은 RuntimeException클래스를 상속한 클래스 입니다. 체크드 익셉션과 달리 Exception처리를 해주지 않아도 컴파일에러가 발생하지 않습니다. 예) NullPointException...등

throws Exception을 하면 메서드를 호출한 곳에서 예외처리를 해줘야합니다.

2021-12-04 14:19 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +    Optional<UserDto> getUserById(String id);
DTO클래스는 Service Layer까지 적용하고 Mapper부터는 domain을 사용해야 맞는 거 같습니다.!

2021-12-04 14:24 UTC, merged