[#5] 로그인/로그아웃 기능 구현
f-lab-edu/DoorRush pull request #40
Opened 2021-12-06 13:45 UTC by ypr821

# [#5] 구현 내용 요약
- 로그인/로그아웃 기능 구현 
- 로그인/로그아웃 기능 테스트 추가

## 리뷰 포인트 
- 

## 체크 포인트
- [X] annotation 설명 주석 달기 
- [ ] 코드 컨벤션 지키기
- [X] 과도한 축약용어 사용하지 않기
- [ ] 객체지향적인 코드 작성

2021-12-07 17:10 UTC, f-lab-jd requested changes
@ypr821 
고생하셨습니다~! 👍 
리뷰드린 내용 전체적으로 확인&덧글 남겨주시고 반영부탁드리겠습니다.

(cc. @yeoonjae)

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +  @PostMapping("/")
@ypr821 
제가 멘토링시간에 드렸던 피드백 반영 부탁드립니다 ㅎㅎ 

(cc. @yeoonjae )

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +  public ResponseEntity<UserDto> joinUser(@RequestBody UserDto userDto) {
@ypr821 
멘토링 시간에 말씀드렸던것처럼 회원가입 응답을 책임지는 클래스롤 별도 생성하면 더 좋을 것 같습니다.

(cc. @yeoonjae )

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +      session.removeAttribute("login");
@ypr821 
`removeAttribute(login)` 의 경우 세션에 저장된 `login` 어트리뷰트만 삭제가 될텐데요.
로그아웃시 세션은 어떻게 되어야할까요? HttpSession 에서 제공하는 다른 기능은 없을까요~?

(cc. @yeoonjae )

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/LoginDto.java
> +  public LoginDto(String id, String password){
@ypr821 
프로젝트 안에서 모든 파라미터가 있는 생성자에 대한 일관성이 있으면 더 좋을 것 같습니다.
1. 롬복의 `@AllArgsConstructor` 사용
2. 직접 생성자 코드 작성 

(cc. @yeoonjae )

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    joinUser(user);
@ypr821 @yeoonjae 
연재님이 저의 지난 리뷰를 반영할때 반영해주시겠지만, joinUser 메소드에 대해 리턴타입이 있어야 합니다. 
mybatis 의 `useGeneratedKeys` 와 `keyProperty` 옵션을 사용한다면 insert 문 한번으로 적절한 리턴타입을 만들어 낼 수 있을 것 같습니다.

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public boolean isDuplicatedId(String id) {
@ypr821 @yeoonjae
연재님이 작성해주신 내용인데 제가 리뷰드리지 못했네요..ㅎㅎ
해당 메소드가 `public` 이어야할 이유가 있을까요?

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public UserDto getUserById(String userId) {
@ypr821 
UserService 안에서 메소드의 파라미터에 대한 일관성을 맞추면 좋을 것 같습니다
1. id (https://github.com/f-lab-edu/DoorRush/pull/40/files#diff-aaa73b75449c139fe36bf146f27de6b9564e4b70d31b00d326041290fac4aa05R38)
2. userId

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    return user.get().toUserDto(user.get());
@ypr821 @yeoonjae 
지난번에 드린 리뷰가 반영되지 않은 연재님 코드인데, 어떤 부분이 변경되어야하는지 잘 아시죠~? ㅎㅎ

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    return user.get().toUserDto(user.get());
@ypr821 @yeoonjae 

수정될 코드이지만, 
```java
    if (user.isEmpty()) {
      throw new UserNotFoundException("회원정보가 없습니다.");
    }
    return user.get().toUserDto(user.get());
```

이 코드는 Optional 의 orElseGetThrow 를 이용한다면 더 간결해질 수 있습니다.

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public HttpStatus login(LoginDto loginDto, HttpSession session) {
@ypr821 
`UserService` 에 있는 login 메소드의 리턴타입을 HttpStatus 으로 선언해주셨는데요.
UserService 에서 HttpStatus 까지도 책임지는게 맞을까요~? 

한번 고민해보시면 좋을 것 같습니다. ㅎㅎ 

(cc. @yeoonjae )

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    String dbPassword = userMapper.getUserPasswordById(loginDto.getId());
@ypr821 
userPassword 를 조회한 결과가 담기는 변수 이름이 dbPassword 인데요 ㅎㅎ 
의도한 내용일까요~? 
(cc. @yeoonjae )

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +      session.setAttribute("login", "yes");
@ypr821 
`login` 이라는  attribute 에 `yes` 라는 값만 할당이 되면 로그인이 되는걸까요? ㅎㅎ 
로그인 성공시 클라이언트는 어떤 정보가 필요할까요? 

 (cc. @yeoonjae )

2021-12-07 17:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    if (dbPassword.equals(loginDto.getPassword())) {
@ypr821 
User 조회시 쿼리에서 Id 와 Password 를 함께 조회한다면, 
App 에서 직접 Password 를 비교하는 연산이 필요 없지 않을까요~? 

 (cc. @yeoonjae )

2021-12-07 17:10 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/login/LoginControllerTest.java
> +    session.setAttribute("login", "yes");
@ypr821 
로그인 되지 않았을때 로그인 하는 경우 테스트는 못하는것 아닌가요~? ㅎㅎ 

(cc. @yeoonjae)

2021-12-07 17:10 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/login/LoginControllerTest.java
> +  protected MockHttpSession session;
@ypr821 
MockHttpSession 은 왜 `protected` 인가요~? ㅎㅎ

(cc. @yeoonjae)

2021-12-07 17:10 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/login/LoginControllerTest.java
> +package com.flab.doorrush.domain.user.login;
@ypr821 

테스트 클래스의 패키지/클래스네임은 테스트하려는 소스와 가급적이면 동일하게 맞추어주어야합니다.


(cc. @yeoonjae)

2021-12-07 17:10 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/login/LoginControllerTest.java
> +public class LoginControllerTest {
@ypr821 
위에 드린 내용과 같은 내용입니다. ㅎㅎ

(cc. @yeoonjae)

2021-12-07 17:10 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/login/LoginTest.java
> +    HttpStatus incorrectInput = userService.login(incorrectLoginDto, session);
@ypr821 
이런 경우 correct 케이스와 incorrect 케이스 각각 테스트메소드를 만들어주는게 좋습니다.

(cc. @yeoonjae)

2021-12-08 01:44 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +  @PostMapping("/")
@f-lab-jd 
넵!!

2021-12-08 01:49 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +  public ResponseEntity<UserDto> joinUser(@RequestBody UserDto userDto) {
넵 반영하겠습니다.!!!

2021-12-08 01:50 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +      session.removeAttribute("login");
@f-lab-jd 
멘토님  session.invalidate(); 메서드로 혹시 세션 무효와 하는거 맞나요?????

2021-12-08 02:02 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/dto/LoginDto.java
> +  public LoginDto(String id, String password){
@f-lab-jd 
@AllArgsConstructor 를 사용하도록 수정하겠습니다!

2021-12-08 02:19 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public UserDto getUserById(String userId) {
@f-lab-jd 
넵 수정했습니다!!

2021-12-08 03:46 UTC, ypr821 commented on src/test/java/com/flab/doorrush/domain/user/login/LoginControllerTest.java
> +  protected MockHttpSession session;
@f-lab-jd 
블로그들의 예시 코드에서 protected 로 지정해서 사용하였기 때문에
깊은 고민없이 사용했습니다... 필요없는 부분인가요???

2021-12-09 13:39 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +      session.removeAttribute("login");
@ypr821  넵 맞습니다~

2021-12-09 13:41 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/login/LoginControllerTest.java
> +  protected MockHttpSession session;
@ypr821 
잘 아시리라 생각하지만 ㅎㅎ `접근 지시제어자` 의 목적과 일관성 있는 코드를 생각하시며 결정하시면 좋을 것 같습니다.
단순 블로그들의 예시코드를 따라 쓰는건 절대 좋은 습관이 아닙니다~!

(cc. @yeoonjae)

2021-12-09 14:12 UTC, f-lab-jd requested changes
@ypr821 
지금까지 반영해주신 리뷰 내용기반으로 추가리뷰드렸습니다. ㅎㅎ
나머지 리뷰들도 잘 반영하고 계시죠~? ㅎㅎ 
리뷰 드린 내용에 질문이 포함된거라면, 가급적 답변도 함께 고려해보시면 좋을 것 같습니다.
잘 하고 계시고 화이팅입니다 푸름님 !!  👍 👍 

(cc. @yeoonjae)

2021-12-09 14:12 UTC, f-lab-jd commented on build.gradle
> +                minimum = 0.5
👍

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +        ELSE 'fail'
@ypr821 
Application 에서 처리할 수 있는 간단한 로직이 이렇게 쿼리에 들어있는건 좋지 않은 방법입니다. 
왜일지 한번 고민해보시고 수정해주세요~

(cc. @ypr821)

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/UserDto.java
> +@AllArgsConstructor // 클래스에 모들 필드에 대한 생성자를 자동으로 생성해준다.
@ypr821 사소하지만 오타가 보이네요..ㅎㅎ

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    if ("success".equals(serviceResult)) {
@ypr821 

1. 변하지 않는 상수나 매직넘버는 별도 변수로 관리되는게 좋습니다.  관련해서는 [Google Java Style 가이드](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) 를 참고하시면 좋습니다. 

2. 서비스에서 `"success"` 라는 스트링을 꼭 응답해야할까요? "success" 가 아닌 경우는 어떤 경우들이 있을까요?

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    if (serviceResult.equals("success")) {
@ypr821 
위에드렸던 내용과 같은 리뷰입니다.

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  String checkUserPasswordById(String id, String password);
@ypr821 
`UserService` 에서 로그인할때 이외에 또 checkUserPassword 를 하는 경우가 있을까요~?
`checkUserPassword` 를 하는 수행하는 책임은 Service 에서 담당하는게 맞지 않을까요~? 


(cc. @yeoonjae )

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  Optional<User> getUserById(String id);
@ypr821 
`getOOO` 형식의 메소드는 잘 아시다시피 모델 클래스의 getter  로도 사용이 되고 Service 에서 조회관련 메소드에서도 사용이 되고 있는데요. Mapper 는 쿼리에 종속적이니 메소드명은 가급적  쿼리 (select, insert, delete, update) 용어를 사용해 네이밍하는것은 어떨까요~?

(cc. @yeoonjae )

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public String login(LoginDto loginDto, HttpSession session) {
@ypr821 
로그인이 실패 하는 케이스는 어떤게 있을까요? 
그 실패하는 케이스를 모두 리턴 타입으로 담으려면 어떻게 해야할까요?
마땅한 리턴타입이 없다면 `void` 타입으로 리턴 하는것도  고려해보시면 좋을 것 같습니다. 

(cc. @yeoonjae )

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public String logout(HttpSession session) {
@ypr821 
login 메소드와 같은 내용의 리뷰입니다.

(cc. @yeoonjae)

2021-12-09 14:12 UTC, f-lab-jd commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    WHERE ID = #{id};
@ypr821 
마지막 뒤에 `;` 는 의도하신건가요? ㅎㅎ

(cc. @yeoonjae)

2021-12-09 14:12 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/user/api/UserControllerTest.java
> +  @Autowired
@ypr821 @yeoonjae 
포맷팅으로 인해 바뀐 코드는 이런식으로 코드 전체가 바뀐거로 나오는데요. ㅎㅎ
이런 경우에 변경이 되었다면 어떤 부분이 변경되었는지, 되지 않았다면 변경내용 없다고 함께 코멘트 남겨주시면 더 좋을 것 같습니다.

2021-12-14 13:55 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public HttpStatus login(LoginDto loginDto, HttpSession session) {
@f-lab-jd 
if문이 생기고 코드가 조금 길어진다는 생각에 Service layer에서 처리하도록 했습니다.

각 layer에 대한 기준이 모호해서 다시 공부하고 있습니다.
Web layer에 해당하는 HttpStatus는 controller에서 처리하는 게 나을 거 같습니다!


멘토님 궁금한 점이 있습니다.
layer 용어가 헷깔립니다ㅜㅜ
Presentation layer == Web layer
Business logic (or Application) layer == Service layer 
Data access layer (or Data) layer == Repository Layer  
이렇게 이해하고 있어도 될까요???

2021-12-14 13:55 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    String dbPassword = userMapper.getUserPasswordById(loginDto.getId());
@f-lab-jd 
네...의도했습니다... 왜냐하면 db에서 검색된 결과값이 담긴 password라서 구분하고 싶었습니다.. !

2021-12-14 13:55 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    if (dbPassword.equals(loginDto.getPassword())) {
@f-lab-jd 
checkUserPasswordById 로 수정해서 쿼리내에서 case문으로 비교하도록 했습니다!!!

2021-12-14 13:55 UTC, ypr821 commented on src/test/java/com/flab/doorrush/domain/user/login/LoginControllerTest.java
> +    session.setAttribute("login", "yes");
그렇네요 ㅜㅜㅎㅎㅎㅎㅎㅎ 감사합니다!!!!

2021-12-14 13:55 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +      session.setAttribute("login", "yes");
@f-lab-jd 
멘토님 저도 이 부분이 고민입니다!! 이슈에 추가했습니다!
access token으로  JWT(JSON Web Token) 주고 받으면 될까요??? 아니면 쿠키정보나 후에 inmemory DB에 저장할 데이터 등이 들어가면 될까요???

2021-12-14 13:55 UTC, ypr821 commented on src/test/java/com/flab/doorrush/domain/user/login/LoginTest.java
> +    HttpStatus incorrectInput = userService.login(incorrectLoginDto, session);
넵 수정하겠습니다

2021-12-14 13:55 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    if ("success".equals(serviceResult)) {
스트링으로 응답하는 것대신 LoginEnum 클래스를 생성해서 그 안에 상수를 모아뒀습니다!!
현재 설정해둔 경우는  SUCCESS(HttpStatus.OK), Fail(HttpStatus.NOT_FOUND); 이 두가지입니다..

2021-12-14 13:55 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  Optional<User> getUserById(String id);
넵 반영하겠습니다!!!!

2021-12-14 13:55 UTC, ypr821 commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +        ELSE 'fail'
@f-lab-jd 
DB에서 처리하는 과정이 많아지면 성능저하가 일어 나기때문입니다!....!!!! 맞나요???

2021-12-14 13:55 UTC, ypr821 commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    WHERE ID = #{id};
@f-lab-jd 
보통 db 쿼리짤때 마지막에 ; 붙였었는데 붙이면 안되는 건가요??

2021-12-14 13:55 UTC, ypr821 commented on src/test/java/com/flab/doorrush/domain/user/api/UserControllerTest.java
> +  @Autowired
@f-lab-jd 
넵 감사합니다 변경내용에 대해 코멘트를 남기도록 하겠습니다!

2021-12-14 13:55 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public String login(LoginDto loginDto, HttpSession session) {
@f-lab-jd 
LoginEnum 타입으로 설정하고 FAIL, SUCCESS 라는 상수를 설정하고 각각 값으로 HttpSatus를 바인딩해봤습니다!

2021-12-14 13:55 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  String checkUserPasswordById(String id, String password);
@f-lab-jd  재사용성이 많이 떨어지는 거 같아서 해당 쿼리는 삭제하고 selectUserByColumns메서드를 추가했습니다.
$를 사용해서 컬럼명을 지정하고 #을 사용해서 값을 입력해서 where절에서 select할 수 있도록 수정했습니다

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public boolean isDuplicatedId(String id) {
@f-lab-jd 
UserService 내부적으로 사용하는 메소드라 public이어야 할 이유는 없는 것 같습니다! 
private으로 변경진행하겠습니다!

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    joinUser(user);
@f-lab-jd 
넵 해당 내용 반영해서 올리겠습니다!

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    return user.get().toUserDto(user.get());
@f-lab-jd 
넵 변경 진행해서 올리도록 하겠습니다!

2021-12-15 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public HttpStatus login(LoginDto loginDto, HttpSession session) {
@ypr821 
스프링 MVC 에서 말하는 일반적인 Layered Architecture 는 말씀하신 내용이 맞습니다.

(cc. @yeoonjae)

2021-12-15 14:46 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    String dbPassword = userMapper.getUserPasswordById(loginDto.getId());
@ypr821 
현재 메소드 블록 안에서 `db 결과` 라는 의미가 반드시 필요할까요~?

2021-12-15 14:47 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +      session.setAttribute("login", "yes");
@ypr821 
멘토링 시간에 답변을 드린 내용이기는한데요. ㅎㅎ 
말씀하신 JWT, 쿠키, In memory DB 에 저장된 데이터랑은 상관이 없고,
로그인 성공 후 클라이언트가 필요한 정보가 무엇인지 잘 고민해보시면 좋을 것 같습니다~!


(cc. @yeoonjae)

2021-12-15 14:50 UTC, f-lab-jd commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +        ELSE 'fail'
@ypr821 
멘토링때 설명드렸던 내용입니다.ㅎㅎ 잘 아시죠~? 

(cc. @yeoonjae)

2021-12-15 14:52 UTC, f-lab-jd commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    WHERE ID = #{id};
@ypr821 
넵 mapper 안의 쿼리에는 붙이지 않습니다. ㅎㅎ

2021-12-15 14:56 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    return ResponseEntity.status(HttpStatus.CREATED).body(userDto);
@ypr821 
응답을 위한 Response 객체 작업은 https://github.com/f-lab-edu/DoorRush/pull/41 에서 진행되는것이죠? ㅎㅎ
포맷팅으로 인해 이것도 변경사항에 포함되어있어서 헷갈리네요;;

(cc. @yeoonjae)

2021-12-15 14:57 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +  @ExceptionHandler
@ypr821 
`ControllderAdvice` 를 사용하여서 `ExceptionHandler` 만 책임지는 클래스를 만드는것은 어떨까요?

(cc. @yeoonjae)

2021-12-15 15:03 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  User selectUserByColumns(String column1, String value1, String column2, String value2);
@ypr821 
https://github.com/f-lab-edu/DoorRush/pull/40#discussion_r765812094 요 리뷰때문에 수정해주신것 같은데요..ㅎㅎ
`UserMapper` 의 책임이 더욱 더 모호해진것 같습니다. 작성한 내용에 의하면, UserMapper 를 호출하는쪽 (현재 프로젝트에서는 UserService) 에서 컬럼명을 일일이 다 알아야할까요?

2021-12-15 15:09 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/exception/loginException/AccountStatusException.java
> +public class AccountStatusException extends RuntimeException {
@ypr821 
당장 사용하지 않는 클래스는 삭제하는게 좋습니다.
그리고 갑작스러운 영어 주석은, 기존 주석들과 일관성이 맞지 않기도 하는데요. ㅎㅎ
현재 사용하지 않고, 나중에 쓰실 목적이라면 명확하게 목적과 의도를 주석에 남겨주시면 좋을 것 같습니다.

2021-12-15 15:10 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/exception/loginException/AccountStatusException.java
> +package com.flab.doorrush.domain.user.exception.loginException;
@ypr821 
exception 패키지 안에 `loginException` 이라는 패키지가 꼭 필요할까요~?

(cc. @yeoonjae)

2021-12-15 15:11 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +      throw new DuplicatedUserIdException("회원가입이 실패하였습니다.");
@ypr821 
요 부분도 연재님 PR 에서 수정되는 부분이라고 생각하겠습니다~

(cc. @yeoonjae)

2021-12-15 15:14 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +            userMapper.selectUserByColumns("ID", loginDto.getId(), "PASSWORD",
@ypr821 
이 부분은 Mapper 쪽 수정되면서 함께 수정해주시면 좋을 것 같습니다. 
login 을 할때 db 를 두번 조회할 필요가 있을까요?

(cc. @yeoonjae)

2021-12-15 15:15 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    Optional<User> userForCheckingId = Optional.ofNullable(
@ypr821 
Optional 을 또 Optional 로 감싼 이유가 있나요..?
Java Optional 에 대해 다시한번 공부하시고 사용해주시면 좋을 것 같습니다. ㅎㅎ

(cc. @yeoonjae)

2021-12-15 15:21 UTC, f-lab-jd requested changes
@ypr821
고생하셨고, 꼼꼼한 테스트코드 좋습니다! 👍  
리뷰드린 내용 다시한번 확인 부탁드리겠습니다~

2021-12-16 04:01 UTC, yeoonjae reviewed
@ypr821 
푸름님 고생하셨습니다!! 👍👍 포맷팅이 적용이 안되어서 코드작성과 리뷰시에 불편을 드려서 죄송합니다 ㅠㅠ

2021-12-16 13:50 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +    return ResponseEntity.status(HttpStatus.CREATED).body(userDto);
네 맞습니다 . 표시를 했어야했는데 죄송합니다!

2021-12-16 13:57 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  User selectUserByColumns(String column1, String value1, String column2, String value2);
UserMapper는 DB에서 실행될 쿼리와 연결되는 메서드를 담고있습니다.

2021-12-16 14:01 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/exception/loginException/AccountStatusException.java
> +package com.flab.doorrush.domain.user.exception.loginException;
@f-lab-jd  필요없나요?? 저는 사용구분을 위해서 필요하다고 생각했습니다!! 불필요하다면 지우겠습니다! 클래스명을 잘지으면 loginException  패키지가 필요가 없을거같기도합니다.

2021-12-16 14:03 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +            userMapper.selectUserByColumns("ID", loginDto.getId(), "PASSWORD",
@f-lab-jd  각 조회시 결과에 따라 exception을 다르게 던지고 싶어서 두번 조회했습니다.
 한번 조회하고 그 조회된 결과 내에서 조건처리를 하는 편이 성능에 좋을 거 같습니다!!  수정하겠습니다.

2021-12-16 14:23 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    Optional<User> userForCheckingId = Optional.ofNullable(
@f-lab-jd  다시 수정했습니다.!!!!

2021-12-16 14:25 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/exception/loginException/AccountStatusException.java
> +public class AccountStatusException extends RuntimeException {
넵 삭제하겠습니다!

2021-12-16 14:44 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +  @ExceptionHandler
@f-lab-jd 
ExceptionHandler  부분만 빠르게 인강보고 적용하였더니 ㅎㅎㅎ 부족한 점이 있습니다 
ControllderAdvice  클래스 생성했습니다!!!

2021-12-16 15:57 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> -
@f-lab-jd 
충돌해결할때 중복으로 잘못 들어간 부분이였습니다.

2021-12-16 15:57 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
@yeoonjae 연재님 안녕하세요!!
멘토님께서 UserMapper의 메소드는 select, insert 등으로 시작하는 메소드명을 지으라고 리뷰 주셨던 내용을 반영했습니다.  getUserById 을 selectUserById 로 수정했습니다.
이전에 반영했었는데 코드를 합치고나서 연재님 부분에 반영이 안되있어서 수정했습니다. 
그리고 연재님 코드에서 문제없도록 getUserById 메소드 호출부분을 selectUserById 메소드 호출로 수정했습니다. 
테스트도  실행 후 문제 없음을 확인했습니다! 
혹시 문제 발견시 피드백 부탁드립니다!

2021-12-16 15:57 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/exception/IdNotFoundException.java
> -
포맷팅 했습니다.

2021-12-16 15:57 UTC, ypr821 commented on src/test/java/com/flab/doorrush/domain/user/api/UserControllerTest.java
불필요한 출력 코드 삭제

2021-12-16 16:01 UTC, ypr821 commented
>

2021-12-16 16:28 UTC, f-lab-jd submitted a review, later dismissed
@ypr821  
정말 고생많으셨습니다 ㅎㅎ 
특히 충돌 해결하는게 보통일이 아니었을텐데.. 👍 👍 
`BaseController` 네이밍 부분만 한번 더 고민해주시고 머지부탁드리겠습니다~!

2021-12-16 16:28 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/BaseController.java
> +@ControllerAdvice
👍

2021-12-16 16:28 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/BaseController.java
> +public class BaseController {
@ypr821 
모든 컨트롤러의 익셉션 처리를 하는 목적의 클래스인데 `BaseController`  보다 더 괜찮은 네이밍은 없을까요~? 

(cc. @yeoonjae)

2021-12-16 16:38 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/api/BaseController.java
> +public class BaseController {
@f-lab-jd  검색을 해보는데 GlobalExceptionHandler는 별로일까요??

2021-12-16 16:39 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/BaseController.java
> +public class BaseController {
@ypr821 좋습니다 ㅎㅎ

2021-12-16 16:50 UTC, yeoonjae approved these changes

2021-12-16 16:51 UTC, merged

2021-12-16 16:52 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
@ypr821 푸름님! 확인했습니다. 감사합니다! 👍