[#39] 회원가입 리뷰 미반영 분 반영
f-lab-edu/DoorRush pull request #41
Opened 2021-12-08 13:57 UTC by yeoonjae

# [#39] 회원가입 리뷰 미반영 분 반영
- DTO, Domain 간의 변환 별도 분리
- Controller에서 회원가입시 리턴타입 받기

## 리뷰 포인트 
- DTO, Domain 간의 변환 별도 분리를 잘 한 것인지 확인 부탁드립니다. 

## 체크 포인트
- [x] annotation 설명 주석 달기 
- [x] 코드 컨벤션 지키기
- [x] 과도한 축약용어 사용하지 않기
- [ ] 객체지향적인 코드 작성

2021-12-09 14:15 UTC, f-lab-jd commented on build.gradle
> +                minimum = 0.7
@yeoonjae 
푸름님 작업하신 내용과 충돌이 나겠네요. ㅎㅎ (실제 실무에서도 자주 있는 일입니다) 
더 뒤에 머지한분께서 충돌을 해결해주셔야할텐데요.
이런 경우에 두분께서 머지 규칙을 정해놓으면 좋습니다. 

1. PR 올린 순서대로 머지한다.
2. 리뷰가 마친 순서대로 머지한다.
3. 기타

(cc. @ypr821)

2021-12-09 14:17 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +        JoinUserResponse userResponse = userService.joinUser(joinUserRequest);
@yeoonjae 
IDE 에 코드 스타일과 포맷터가 잘 적용된걸까요~?

2021-12-09 14:19 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +    boolean getCountById(String id);
@yeoonjae 
boolean 타입을 리턴하나요..? ㅎㅎ
그리고 count 를 리턴하는 Mapper 메소드의 경우에는 `count` 자체를 동사형로 사용해도 좋습니다.

(cc. @ypr821)

2021-12-09 14:20 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/request/JoinUserRequest.java
> +    public static User toUser(JoinUserRequest joinUserRequest) {
@yeoonjae 
static 메소드로 선언한 이유가 있으신가요~?

2021-12-09 14:22 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/response/FindUserResponse.java
> +    public static FindUserResponse createFindUserResponse(User user) {
@yeoonjae 
https://github.com/f-lab-edu/DoorRush/pull/41/files#r765834327 와 같은 리뷰입니다.

2021-12-09 14:24 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/request/JoinUserRequest.java
> +    private String loginId;
@yeoonjae 
https://github.com/f-lab-edu/DoorRush/pull/41/files#diff-46b636ef3eb92ceba9f26216f7ba078f76fc02e0757b61bcc0e22e0f18749698R13
Response DTO 에는 `final` 을 붙였는데, Request DTO 에는 안붙이신 이유가 있으신가요~? 
소소한 내용이지만 이러한 것까지  일관성을 맞추시는 습관을 들이면 좋습니다.

(cc. @ypr821)

2021-12-09 14:24 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/response/JoinUserResponse.java
> +    public static JoinUserResponse createJoinUserResponse(User user) {
@yeoonjae 
https://github.com/f-lab-edu/DoorRush/pull/41/files#r765835865 와 같은 리뷰입니다. ㅎㅎ

2021-12-09 14:26 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +        boolean isDuplicated = isDuplicatedId(user.getLoginId());
@yeoonjae 
가독성때문에 별도 변수로 빼신거라면, 별도로 boolean 변수로 빼지 않아도 충분히 가독성있을 것 같습니다.

(cc. @ypr821)

2021-12-09 14:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
>      public boolean isDuplicatedId(String id) {
@yeoonjae 
지난번에도 드린 리뷰인것 같은데 `public` 일 필요가 있을까요?

2021-12-09 14:28 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +        return userMapper.getCountById(id);
@yeoonjae 
회원가입 여부를 알기 위해 `getUserById` 가 아니라 count 를 해야하는 이유가 있나요~? 

(cc. @ypr821 )

2021-12-09 14:29 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +            .orElseThrow(() -> new UserNotFoundException("회원정보가 없습니다."));
@yeoonjae  👍 
이렇게 던진 예외들은 어디서 어떻게 처리하는게 좋을까요?

(cc. @ypr821 )

2021-12-09 14:32 UTC, f-lab-jd commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    keyProperty="userSeq" useGeneratedKeys="true">
@yeoonjae  👍 
직접 찾아 보고 쓰셔서 연재님은 각 속성이 어떤 역할을 하는지 잘 아시겠지만 
푸름님께서도 이해하시기 위해 어떤 역할을 하고 왜 썼는지 한번 설명해주실 수 있으신가요~?

(cc. @ypr821)

2021-12-09 14:33 UTC, f-lab-jd requested changes
@yeoonjae 
고생하셨습니다~! 👍 
리뷰드린 내용 한번 더 확인해주심 좋을 것 같습니다. ㅎㅎ

2021-12-10 11:49 UTC, yeoonjae commented
@f-lab-jd @ypr821 
https://github.com/f-lab-edu/DoorRush/pull/41/commits/b7fe0498f1dd88f25c39f107cff85cf4405c2537
리뷰내용 반영하여 커밋했습니다!

2021-12-12 10:37 UTC, f-lab-jd requested changes
@yeoonjae 
고생하셨습니다~! 리뷰 드린 내용 모두 다시 확인부탁드리겠습니다. ㅎㅎ 
그리고 dto 에 `@NoArgsConsturctor` 를 사용하신 이유는 무엇인가요~?
(cc. @ypr821)

2021-12-14 13:52 UTC, f-lab-jd commented on build.gradle
> +                minimum = 0.7
test

2021-12-14 13:54 UTC, ypr821 commented on build.gradle
> +                minimum = 0.7
안녕하세요 @yeoonjae 님 
설정이 METHOD ->CLASS , 5 -> 7로 가는 건가요 ??? 
이전에 혹시 말씀 주셨었나요??? 
멘토님 피드백 이후로 5로 다시 올려두고 작업 중이라서요 상의가 필요할 거 같습니다!!

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +            .orElseThrow(() -> new UserNotFoundException("회원정보가 없습니다."));
@f-lab-jd 
@ControllerAdvice 또는 @ExceptionHandler 를 통해 예외에 대한 응답을 처리합니다! 

@ExceptionHandler는 선언한 Controller 안에서만 예외가 처리 가능하며, 예외에 대한 응답을 정의할 수 있습니다. 
@ControllerAdvice는 전역적으로 처리할 수 있는 어노테이션으로 여러개의 Controller만 적용도 가능한 어노테이션입니다. 예외처리뿐만 아니라 바인딩 설정 모델 객체 설정 등 다양한 설정을 할 수 있습니다.

2021-12-14 14:00 UTC, yeoonjae commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    keyProperty="userSeq" useGeneratedKeys="true">
@f-lab-jd @ypr821 넵넵 푸름님 ! 아래에 속성에 대한 설명 작성했습니다 !

* `useGeneratedKeys` : insert, update에만 적용되는 속성으로 데이터베이스 에서 내부적으로 생성한 키(자동증가) 를 받는 `JDBC getGeneratedKeys` 메소드를 사용하도록 설정하는 속성입니다. 기본값을 false 이며, true 로 설정할 경우 적용됩니다. 

* `keyProperty` : insert, update에만 적용되는 속성으로 `getGeneratedKeys` 메소드나 insert 구문의 `selectKey` 에 의해 리턴된 키를 셋팅할 프로퍼티를 지정합니다. 기본값은 설정이 되어있지 않으며, 프로퍼티명에 콤마를 이용하여 여러개의 칼럼도 사용할 수 있습니다. 

코드에 작성한 insert 문은 `useGeneratedKeys` 를 true로 설정하여 자동증가 키값을 받도록 설정하였고, `keyProperty` 를 `userSeq`로 설정함으로써 자동증가 키 값을 `userSeq` 가 받습니다! 


참고 사이트
https://mybatis.org/mybatis-3/ko/sqlmap-xml.html

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +        boolean isDuplicated = isDuplicatedId(user.getLoginId());
@f-lab-jd 
네 반영하겠습니다!

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
>      public boolean isDuplicatedId(String id) {
@f-lab-jd 
리뷰반영시 누락된 것 같습니다. private 으로 변경하여 반영하도록 하겠습니다!

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dto/request/JoinUserRequest.java
> +    public static User toUser(JoinUserRequest joinUserRequest) {
@f-lab-jd 
인스턴스를 생성하지 않아도 사용이 가능하도록 하기 위해서 사용했습니다. 혹시 제거가 필요할까요?

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +    boolean getCountById(String id);
@f-lab-jd 
넵 boolean 타입을 리턴하도록 sql을 변경했었는데 메소드명 변경이 누락되었습니다.. 다시 count를 리턴하도록 변경하고 메소드명도 변경 후 반영하도록 하겠습니다!

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dto/request/JoinUserRequest.java
> +    private String loginId;
@f-lab-jd 
response DTO는 DB를 통해 조회된 것이라 변경이 되면 안된다고 생각하여 final을 붙였습니다! 
일관성 있게 final을 제거하도록 하겠습니다..!!

2021-12-14 14:00 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +        return userMapper.getCountById(id);
@f-lab-jd 
`getUserById` 는 회원이 없을 경우에 에러를 발생시키기 때문에 `countById` 메소드를 사용했습니다. 현재는 `getUserById`를 사용하지 않지만 추후에 추가될 `회원정보 찾기` 에서 사용될 것 같아서 제거하지 않았습니다!

2021-12-15 05:40 UTC, yeoonjae commented
@f-lab-jd 
Dto 클래스에서 `static` 을 뺐을 때 객체 생성을 위해 `@NoArgsConsturctor` 를 사용했었습니다. 
Dto 클래스에서 `static` 을 사용하거나 어제 멘토링 시간에 말씀해주신 `mapStruct` 를 사용한다면 제거해도 될 것 같습니다. 
`Object Mapping` 에 대해서 메소드와  mapStruct 중 어떤 것에 대해서 사용할 지는 고민해본 뒤 다시 적용하도록 하겠습니다!

2021-12-15 09:39 UTC, yeoonjae commented
https://github.com/f-lab-edu/DoorRush/pull/41/commits/98fd9a0189791a6cb28a5097fbf5379be0285983
@f-lab-jd 
리뷰주신 내용 반영했습니다!
멘토님께서 말씀해주신 `mapStruct` 를 찾아봤습니다.  흥미로운 내용들이 많아서 적용을 해봤었는데, 변환이 되는 객체가 있을 때마다 mapper 클래스를 따로 생성해준다는 점과 변환의 대상이 되는 두개의 클래스에 모두 기본생성자 또는 빌더객체가 들어가야 해서 기존에 사용했던 메소드를 이용해서 구현했습니다. 

그리고, 이전에 주셨던 리뷰처럼 굳이 isDuplicatedId()` 메소드가 없어도  `getUserById()` 를 사용하면 된다고 생각되어서 제거하였습니다!

2021-12-15 15:23 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/request/JoinUserRequest.java
> +    public static User toUser(JoinUserRequest joinUserRequest) {
@yeoonjae 
멘토링 시간에 답변을 드렸는데, 혹시 이해가 안되신다면 말씀해주세요~!

(cc. @ypr821)

2021-12-15 15:24 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/request/JoinUserRequest.java
> +    private String loginId;
@yeoonjae 
어차피 불변객체일텐데 일관성있게 final 을 붙이는게 좋지않을까요? ㅎㅎ 
그치만 중요한건 일관성이니, 빼는거로 지키시면 좋을 것 같습니다.

(Cc. @ypr821)

2021-12-15 15:30 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
@yeoonjae 
이제 발견하였는데, 요기 불필요한 공백라인이 보이네요 ㅎㅎ

2021-12-15 15:34 UTC, f-lab-jd commented
@yeoonjae 
고생하셨습니다. 👍 
지난번에 리뷰드린 내용인데..ㅎㅎ 연재님 코드에 포맷터가 적용되지 않은것같습니다. 
포맷터 적용후에 승인하도록 하겠습니다.

근데 걱정인거는.. @ypr821 님 코드랑 정말 많이 충돌이나서 해결하는게 꽤나 일일것같네요. ㅎㅎ

2021-12-15 19:46 UTC, yeoonjae reviewed
@f-lab-jd 
감사합니다. 지금까지 포맷터 잘 적용된 줄 알았는데,, 아닌가봅니다,, 포맷터를 다시 적용해보겠습니다 ! 그리고,, 제가 코드를 많이 변경해서 정말 충돌이 많이 날 것 같습니다,,,...,,..ㅠㅠ

2021-12-15 19:46 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dto/request/JoinUserRequest.java
> +    private String loginId;
@f-lab-jd 
넵!! 일관성있는 코드 !! 늘 인지하겠습니다!

2021-12-15 19:46 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
@f-lab-jd 
포매터 적용하면서 수정하여 같이 올리겠습니다. !

2021-12-16 03:53 UTC, yeoonjae commented
@f-lab-jd 
포맷터를 다시 적용하고 보니 정말 하나도 적용이 되지 않았었습니다,,, 같은 리뷰 여러번 드리게 해서 죄송합니다,,, 
코드는 변경사항 없고 불필요한 개행과 포맷터만 변경하였습니다.

2021-12-16 13:13 UTC, f-lab-jd approved these changes
👍

2021-12-16 13:34 UTC, merged

2021-12-16 13:40 UTC, ypr821 commented
고생하셨습니다 연재님!.. 충돌.. 충돌.. ... 화이팅..!!