[#20] 비밀번호 암호화 적용
f-lab-edu/DoorRush pull request #44
Opened 2021-12-17 16:06 UTC by yeoonjae

# [#21] 비밀번호 암호화 적용
- spring security config 파일 작성
- spring security 적용하여 회원가입 시 비밀번호 암호화 

## 리뷰 포인트 
- 비밀번호 암호화 적용 및 spring security 사용을 위한 config 파일을 작성했습니다.

## 체크 포인트
- [x] annotation 설명 주석 달기 
- [x] 코드 컨벤션 지키기
- [x] 과도한 축약용어 사용하지 않기
- [ ] 객체지향적인 코드 작성

2021-12-17 16:11 UTC, yeoonjae commented
@f-lab-jd @ypr821 
스프링 시큐리티를 적용하며 스프링 시큐리티 동작방법에 대해 정리했습니다. 

https://yeoonjae.tistory.com/entry/Spring-%EC%8A%A4%ED%94%84%EB%A7%81-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0

2021-12-19 12:50 UTC, f-lab-jd requested changes
@yeoonjae 
고생하셨습니다~ 리뷰 드린 내용 중에 이해 안되시는게 있다면 편히 말씀해주세요~!

2021-12-19 12:50 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/config/WebSecurityConfigurer.java
> +package com.flab.doorrush.domain.config;
@yeoonjae 
`config` 패키지가 `domain` 패키지 안에 있어야하는 이유가 있을까요~?

(cc. @ypr821)

2021-12-19 12:50 UTC, f-lab-jd commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security:2.6.1'
@yeoonjae @ypr821 
제가 기존에 `build.gradle` 의존 라이브러리 관련해서 꼼꼼히 리뷰를 드리지 못했네요..ㅎㅎ 
의존 라이브러리의 버전은 어떻게 관리하는게 좋을까요? 스프링 부트에서는 어떠한 편의를 제공할까요?
한번 고민해보시고, 멘토링시간에 이야기 나누어보면 좋을 것 같습니다.

2021-12-19 12:50 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/config/WebSecurityConfigurer.java
> +        .headers().frameOptions().disable();
@yeoonjae 
1. Spring Security 를 왜 사용했는지.  Spring Security 를 `꼭` 써야하는지.
2. Spring Security 설정한 내용이 무엇인지.

관련해서 한번 풀어서 설명해주실 수 있을까요~? ㅎㅎ
블로그에 `Spring Security` 동장방식 및 주요 피쳐에 대해 잘 정리해주셨는데요.  👍 
이를 DoorRush 에서는 어떠한 설정으로 어떻게 동작을 하는지도 함께 공유해주시면 함께 협업하는 @ypr821 님께도 큰 도움이 될 것 같습니다.

2021-12-19 12:50 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/config/WebSecurityConfigurer.java
> +    return new BCryptPasswordEncoder();
@yeoonjae 
`BCryptPasswordEncoder` 는 어떠한 방식으로 암호화하는지 설명해주실 수 있으실까요~? 

(cc. @ypr821)

2021-12-19 12:50 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    joinUserRequest.setPassword(passwordEncoder.encode(joinUserRequest.getPassword()));
@yeoonjae 
로그인시에는 암호화/복호화가 필요없을까요~?

(cc. @ypr821)

2021-12-20 04:02 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/config/WebSecurityConfigurer.java
> +    return new BCryptPasswordEncoder();
@f-lab-jd  @ypr821 
`BCryptPasswordEncoder` 는 `PasswordEncoder` 인터페이스를 구현한 것으로 BCrypt 해시 함수를 사용하여 암호를 해시 합니다. Bruteforce attack이나 Rainbow table attack과 같은 Password Cracking에 대한 저항력을 높이기 위해 의도적으로 느리게 설정되어 있습니다. `BCryptPasswordEncoder` 의 속도는 강도에 따라서 조정할 수 있게끔 되어있습니다. 4~31 로 설정할 수 있으며 기본값은 10으로 설정되어있습니다. 

> `bcrypt` 
> * Blowfish 암호를 기반으로 설계된 암호화 함수이며 현재까지 사용중인 가장 강력한 해시 메커니즘 중 하나입니다. 
> * 반복횟수를 늘려 연산 속도를 늦출 수 있어 연산능력이 증가하더라도 Bruteforce attack 에 대비할 수 있습니다.

2021-12-20 04:02 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/config/WebSecurityConfigurer.java
> +        .headers().frameOptions().disable();
@f-lab-jd @ypr821 
1. Spring Security는 보안과 관련하여 많은 옵션을 제공해주어 개발자가 일일이 보안 로직을 구현하지 않아도 된다는 점에서 사용하게 되었습니다. 보안관련한 인증과 인가에 대해 기본적으로 필터들이 제공됩니다. 
2. 우선 위의 `config(HttpSecurity http)` 설정은 Filter chain에 접근하여 url 인증 및 인가 처리 시행하는 메소드로 상속받은 `WebSecurityConfigurerAdapter` 의 메소드를 오버라이딩 한 것입니다. 이를 통해 URL 별 또는 사용자별 접근권한을 커스터마이징 할 수 있습니다. 

* `authorizeRequests().antMatchers("/h2-console/**").permitAll()` : 이는 접근 권한을 설정하는 것입니다. antMatchers를 사용하여 url을 지정할 수 있고 그 뒤에 `permitAll()` 은 모든 접근을 허용한다는 것입니다. 따라서 저는 h2 디비를 이용하기 위해 h2-console url은 모두 허용이 가능하도록 설정하였습니다. `permitAll()` 외에도 `authenticated()` , `access("hasRole('ROLE_ADMIN')")` 와 같은 설정으로 인증이 필요함과 해당 권한을 가진 사람만 접근 가능하도록 설정도 가능합니다. 
* `.csrf().disable()` : csrf 공격 방지 설정으로 인해 기존에 작동되던 users api 중 POST, PUT, PATCH, DELETE method request가 작동되지 않게 됩니다. 따라서 이를 disable() 시킴으로써 작동하지 않도록 설정했습니다. 
* `formLogin().disable()` : 스프링 시큐리티를 적용후 localhost:8080을 띄우면 자체적으로 제공해주는 로그인화면이 나오게 됩니다. yml 파일에 아이디 비밀번호를 설정할 수도 있지만 disable()을 설정함으로써 아예 사용하지 않게끔 설정하였습니다. 
* headers().frameOptions().disable() : 이 부분은 완벽히 이해가 되지 않아서 좀 더 알아본 뒤에 다시 답변 달도록 하겠습니다!

2021-12-20 04:02 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/config/WebSecurityConfigurer.java
> +package com.flab.doorrush.domain.config;
@f-lab-jd 
전체적인 설정파일이니 domain 밖으로 뺴서 만드는 것이 나을 것 같습니다!

2021-12-20 04:02 UTC, yeoonjae commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security:2.6.1'
@f-lab-jd 
스프링 시큐리티 공식문서를 봤을 때 버전관리는 
`ext['spring-security.version']='5.6.0'`
이렇게 하라고 적혀져 있었습니다. 이미 뒤에 버전이 적혀져 있어서 우선 일관성있게 뒤에 적었습니다!
좀 더 찾아보고 고민해보겠습니다.

2021-12-20 04:02 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    joinUserRequest.setPassword(passwordEncoder.encode(joinUserRequest.getPassword()));
@f-lab-jd 
필요할 것 같았지만 푸름님께서 구현한 기능이라 우선 회원가입만 진행했었습니다. 이는 푸름님과 얘기 나눠보겠습니다!

2021-12-20 15:33 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    joinUserRequest.setPassword(passwordEncoder.encode(joinUserRequest.getPassword()));
연재님께서 머지 하시면 로그인 기능에도 암호화/복호화 과정을 추가하겠습니다

2021-12-21 14:20 UTC, f-lab-jd commented
@yeoonjae 
1. 스프링 부트 의존성 
2. spring-security 가 아닌 암호화 모듈 의존 

멘토링 시간에 말씀드렸던것처럼, 위 두가지에 대해서 수정 후 반영부탁드려요~

2021-12-21 19:03 UTC, yeoonjae commented
@f-lab-jd @ypr821 
스프링 부트 의존성과 스프링 시큐리티 암호화 모듈에 의존하도록 변경하였습니다! (https://github.com/f-lab-edu/DoorRush/pull/44/commits/03188d212a58d98a1970911a09c7a9483ec0e12d) 
 그리고 회원가입 시 예외에 대한 ExceptionHandler 도 같이 구현하였습니다. (https://github.com/f-lab-edu/DoorRush/pull/44/commits/06a5d0b403beb10ef4f1ff4f6ac56ee58b235188)

2021-12-23 11:23 UTC, f-lab-jd approved these changes
👍

2021-12-23 11:33 UTC, merged