#15 자동로그인 기능 구현
f-lab-edu/DoorRush pull request #55
Opened 2021-12-28 06:10 UTC by ypr821

# [#15] 구현 내용 요약
- AutoLoginInterceptor 생성
- 자동로그인 기능 메소드 추가 
- 자동로그인 기능 테스트 추가
- 암호화 적용
- @DisplayName 적용

## 리뷰 포인트 
- 전체 로직, 테스트 코드 리뷰가 시급합니다 !!! 

## 체크 포인트
- [X] annotation 설명 주석 달기 
- [X] 코드 컨벤션 지키기
- [X] 과도한 축약용어 사용하지 않기
- [X] 객체지향적인 코드 작성

close #15

2022-01-05 14:52 UTC, f-lab-jd reviewed
리뷰 submit 하는걸 깜빡했네요..ㅎㅎ

2022-01-05 14:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +      autoLoginCookie.setMaxAge(60 * 60 * 24 * 30);
상수

2022-01-05 14:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +    if (autoLoginRequest.isAutoLogin()) {
cookieUtils

2022-01-05 14:52 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +      String autoLoginCookieValue = URLEncoder.encode(user.getUserSeq() + "",
`String.valueOf()`

2022-01-08 12:58 UTC, f-lab-jd requested changes
@ypr821 
고생하셨습니다~! 리뷰 내용 한번 봐주시고 이해가 안되는 부분이 있다면 말씀해주세요. 
아 그리고 혹시 `AutoLoginInterceptor` 가 로그인시에 현재 정상 동작하나요~?!

2022-01-08 12:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
>      LoginRequest loginRequest = new LoginRequest(autoLoginRequest.getId(),
@ypr821 
`AutoLoginRequest` 와 `LoginRequest` 를 나누어야하는 이유가 있을까요~? 
`LoginRequest` 하나로 관리한다면, 요 로직도 사라지고 더 간결할 것 같습니다.

(cc. @yeoonjae)

2022-01-08 12:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
>      authenticationService.login(loginRequest, session);
@ypr821 
login 메소드에 대한 리턴타입이 `User` 가 된다면 
https://github.com/f-lab-edu/DoorRush/pull/55/commits/c74fa0f926b9cd821e1b78e210d4a7e29bf6b03d#diff-44d5adde18eb29f1ab71f6d593e4d38fe6f1fe1afe16e22653af88a509df0d09R38

요기에서 한번 더 DB 에서 데이터를 가져올 필요가 없을 것 같습니다.

(cc. @yeoonjae)

2022-01-08 12:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +      Cookie autoLoginCookie = getAutoLoginCookie(user);
👍

2022-01-08 12:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/exception/GlobalExceptionHandler.java
> +    log.error("등록된 아이디가 없습니다.", IdNotFoundException.class);
@ypr821 
error 메소드의 두번재 파라미터에 클래스를 넘기어서 어떤 내용을 기대하나요~? 
stack trace 를 볼 수 있도록 exception 객체를 넘기는게 맞지 않을까요? 

(cc. @yeoonjae)

2022-01-08 12:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/CookieUtils.java
> +  final static int COOKIE_MAX_AGE = 60 * 60 * 24 * 30;
@ypr821 
어떤 쿠키의 MAX AGE 인지 변수명에서 알 수 있으면 더 좋을 것 같습니다. 

(cc. @yeoonjae)

2022-01-08 12:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/CookieUtils.java
> +    Cookie autoLoginCookie = new Cookie("AUTOLOGIN", autoLoginCookieValue);
@ypr821 
1. cookieValue 를 UrlEncoder 로 encode 하는 목적은 무엇인가요~?
2. AUTOLOGIN 이라는 쿠키이름에 userSeq 값을 저장하여서 자동로그인 여부를 판단하는데요. 쿠키는 브라우져에 직접 노출이되고, 사용자가 수정을 할 수 있기 때문에 보안에 위험하지 않을까요~? 예를들면, 악의적인 사용자가 "AUTOLOGIN" 이라는 쿠키이름을 보고 로그인과 관련된 쿠키라는 것을 파악하고, 숫자(seq) 가 저장되어있는것을 보고 이를 여러 숫자를 대입한다면..ㅎㅎ 본인이 아닌 다른 유저의 계정으로 로그인도 가능할 것 같습니다. 어떻게 이를 막을 수 있을까요~?

(cc. @yeoonjae)

2022-01-08 12:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/CookieUtils.java
> +        StandardCharsets.UTF_8);
@ypr821 포맷터가 개행시킨걸까요~? 아니라면, 불필요한 개행이 들어간 것 같습니다. ㅎㅎ

2022-01-09 12:18 UTC, yeoonjae commented
자동로그인 기능 인터셉터부터 쿠키까지 정말 고생 많으셨습니다 ! 👍

2022-01-09 13:11 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
>      authenticationService.login(loginRequest, session);
리뷰 정말 감사합니다 !!!!!  수정했습니다!!

2022-01-09 13:48 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
>      LoginRequest loginRequest = new LoginRequest(autoLoginRequest.getId(),
처음에 객체지향적으로 구현하지 못한 거 같습니다 ㅜ DTO 가 두개 인데 .... 뭔가 하나로 합치니까 수정해야할 코드가 꽤 많네요.. ㅜ

2022-01-09 13:49 UTC, ypr821 commented on src/main/java/com/flab/doorrush/global/util/CookieUtils.java
> +  final static int COOKIE_MAX_AGE = 60 * 60 * 24 * 30;
넵 수정하겠습니다!!!

2022-01-09 13:50 UTC, ypr821 commented on src/main/java/com/flab/doorrush/global/util/CookieUtils.java
> +        StandardCharsets.UTF_8);
수정하겠습니다!

2022-01-09 13:56 UTC, ypr821 commented on src/main/java/com/flab/doorrush/global/exception/GlobalExceptionHandler.java
> +    log.error("등록된 아이디가 없습니다.", IdNotFoundException.class);
객체를 넘기는게 더 좋은 로그를 남길 수 있을 거같습니다 ㅎㅎ 감사합니다

2022-01-09 16:01 UTC, ypr821 commented on src/main/java/com/flab/doorrush/global/util/CookieUtils.java
> +    Cookie autoLoginCookie = new Cookie("AUTOLOGIN", autoLoginCookieValue);
@f-lab-jd 
1. 쿠키값으로 String을 담아서 요청으로 보냈을때 문작 깨져서 UrlEncoder으로 Charset을 맞춰줬었습니다.. 
2. 쿠키 값을 password encoding을해서 담았는 데 복호화하는 방법이 없어서.. 고민중입니다.

2022-01-10 15:39 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/CookieUtils.java
> +    Cookie autoLoginCookie = new Cookie("AUTOLOGIN", autoLoginCookieValue);
@ypr821 
1. 넵. 👍 
2. 서버만 아는 key 로 Cookie 를 암호화/복호화하는 방법은 어떤가요~?

2022-01-15 11:53 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +  public ResponseEntity<BasicResponse> login(@Valid @RequestBody LoginRequest loginRequest,
@ypr821 BasicResponse 는 제네릭을 사용하는 parameterized class 아닌가요? ㅎㅎ 

(cc. @yeoonjae)

2022-01-15 11:55 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AutoLoginInterceptor.java
> +      return result;
@ypr821 항상 true 값이기 때문에 간단히 true 라고 적어도 좋을 것 같습니다.

(cc. @yeoonjae)

2022-01-15 11:57 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/service/AuthenticationService.java
>      }
@ypr821 이번에 작업하신 내용은 아니지만..ㅎㅎ
https://github.com/f-lab-edu/DoorRush/pull/55/commits/57f6b7a8bd5338e76e1a31815e7b96a2c55163e8#diff-10f12ea24cce22f4de952af4e983fda99ce938de382b670a9c807ecd2002911fR35 요 부분의 "loginId" 에 대해 리뷰드렸던것 혹시 기억나시나요~?! 
(cc. @yeoonjae)

2022-01-15 11:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AutoLoginInterceptor.java
>        if (cookie.getName().equals("AUTOLOGIN")) {
@ypr821 "AUTOLOGIN"은 상수로 선언하는게 더 좋을 것 같습니다.

(cc. @yeoonjae)

2022-01-15 12:00 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/service/AuthenticationService.java
> +  public User login(LoginRequest loginRequest, @NotNull HttpSession session) {
@ypr821 
엇 근데 자동로그인을 한 경우 login 메소드가 두번 호출되는것 아닌가요..? ㅎㅎ 
요청이 들어왔을때 흐름이 어떻게 되는지 한번 말씀해주실 수 있으실까요~?

(cc. @yeoonjae)

2022-01-15 12:07 UTC, f-lab-jd commented on src/test/java/com/flab/doorrush/domain/authentication/api/AuthenticationControllerTest.java
> +    LoginRequest loginRequest = new LoginRequest("test6", "test6pw", false);
@ypr821 
당장 고쳐야하는 내용은 아니지만.. 파라미터가 많아질 수록 생성자를 사용했을때 가독성은 떨어지기 때문에 builder 를 활용해보아도 좋을 것 같습니다.

(cc. @yeoonjae)

2022-01-15 12:08 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +  final static String AESIV = "jdpureummyeonjae"; //16byte
@ypr821 이 부분을 phase (개발/운영)마다 다르게 하려면 어떻게 해야할까요~? 

(cc. @yeoonjae)

2022-01-15 12:11 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +    String encryptedValueToString = "";
@ypr821 빈 스트링으로 변수를 선언하지 않고 결과를 리턴하는 방법은 없을까요~? 

(cc. @yeoonjae)

2022-01-15 12:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +      SecretKeySpec keySpec = new SecretKeySpec(AESKEY.getBytes(), "AES");
@ypr821 
AES 는 변하지않는 문자열 (매직 리터럴) 인 것 같네요.ㅎㅎ

(cc. @yeoonjae)

2022-01-15 12:13 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +  private String getAESKEY() {
@ypr821  private getter 를 만드신 이유가 무엇인가요~? 

(cc. @yeoonjae)

2022-01-15 12:13 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +    SecurityUtils securityUtils = new SecurityUtils();
@ypr821 
SecurityUtils 클래스를 매번 호출할때마다 생성해야할까요~? 

(cc. @yeoonjae)

2022-01-17 13:50 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +  public ResponseEntity<BasicResponse> login(@Valid @RequestBody LoginRequest loginRequest,
@f-lab-jd 
담을 데이터가 없어가지구요 그냥  BasicResponse 만 넣었습니다.
<?> 이런식으로 라도 남길까요??

2022-01-17 13:50 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/authentication/api/AutoLoginInterceptor.java
> +      return result;
@f-lab-jd  넵!!!

2022-01-18 11:30 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +  public ResponseEntity<BasicResponse> login(@Valid @RequestBody LoginRequest loginRequest,
@ypr821 응답타입이 없는것이라면 Void  가 적당해보입니다.

2022-01-18 14:46 UTC, ypr821 commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +  private String getAESKEY() {
fnal이  있어서 지웠습니다!!  순간 혼란이....왔어요

2022-01-18 14:47 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +  public ResponseEntity<BasicResponse> login(@Valid @RequestBody LoginRequest loginRequest,
HttpStatus 는 보내야하는데 void로 해도 되나요??

2022-01-18 14:57 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/authentication/service/AuthenticationService.java
>      }
@f-lab-jd  
리뷰가 보이지가 않아서요ㅜㅜ 혹시 어떤 내용이였나요??
상수로 바꿔야하나요??? loginId 네이밍이 문제였나요??

2022-01-18 15:06 UTC, ypr821 commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +    SecurityUtils securityUtils = new SecurityUtils();
@f-lab-jd 
속성들을 static으로 바꾸고 객체를 생성하지않고 상수를 사용하도록 수정했습니다!

2022-01-18 15:19 UTC, ypr821 commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +  final static String AESIV = "jdpureummyeonjae"; //16byte
@f-lab-jd 
오늘 멘토링에서 말씀해주신것처럼 application.yml에서 환경에 맞게 값을 담을 수 있도록 하면 될 거 같습니다. 
궁금한점이 예를 들면 개발, 운영 이렇게 다르게 하면 @ConfigurationProperties( ) 파라미터 안의 값만 달리해서 적용 하는 거 맞나요??
@ConfigurationProperties("개발")
 @ConfigurationProperties("운영")

2022-01-18 15:19 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/authentication/service/AuthenticationService.java
> +  public User login(LoginRequest loginRequest, @NotNull HttpSession session) {
@f-lab-jd  넵 그려보겠습니다.  
멘토님 생각해보니까 로그인 후에 사용할 수 있는 기능을 호출할때 인증 여부를 확인하는 로직이 필요합니다...
현재 AutoLoginInterceptor는 로그인 호출에 자동로그인을 위해서만 존재하네요...

2022-01-21 02:11 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/api/AuthenticationController.java
> +  public ResponseEntity<BasicResponse> login(@Valid @RequestBody LoginRequest loginRequest,
@ypr821 ResponseEntity 는 유지한채 BasicResponse 의 파라미터에 대해서 이야기드렸습니다 ㅎㅎ

2022-01-21 02:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/service/AuthenticationService.java
>      }
@ypr821 
1. session 에 담긴 값을 object 로 변경하는 것 + 네이밍
2. 상수
두가지 입니다~!

2022-01-21 02:13 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/service/AuthenticationService.java
> +  public User login(LoginRequest loginRequest, @NotNull HttpSession session) {
@ypr821 
넵 해당 로직은 다음 PR 에 작성해주시면 좋을 것 같습니다~

2022-01-21 02:15 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/util/SecurityUtils.java
> +  final static String AESIV = "jdpureummyeonjae"; //16byte
@ypr821 
음 해당 방식보다는 application 전체가 영향받을 수 있도록, application 실행시 active-profile 을 결정할 수 있도록 진행하는게 더 좋지않을까요? ㅎㅎ spring profile 관련해서 좀 더 찾아보시고 이해가 안되시는 부분이 있다면 말씀해주세요~!

2022-01-21 02:18 UTC, f-lab-jd submitted a review, later dismissed
👍 
푸름님 고생하셨습니다. 나머지 리뷰 내용들은 다음 PR 에 반영하시면 좋을 것 같습니다 ㅎㅎ

2022-01-21 02:25 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/service/AuthenticationService.java
> +  public final  String LOGIN_SESSION = "loginId";
@ypr821 
포맷터가 적용되지 않은 것 같습니다..ㅎㅎ

2022-01-21 08:38 UTC, yeoonjae approved these changes
정말 고생 많으셨습니다 푸름님 !!

2022-01-21 08:38 UTC, merged