[#54] 회원 주소 관련 기능 구현
f-lab-edu/DoorRush pull request #56
Opened 2022-01-05 19:19 UTC by yeoonjae

# [#54] 회원 주소 관련 기능 구현
- 주소 조회
- 주소 등록
- 주소 삭제

## 리뷰 포인트 
- 회원 주소 관련 기능 CRD 구현
- 기본 주소지로 설정 시 다른 주소지는 기본주소지가 아닌 것으로 update
- 트랜잭션을 이용해서 구현했습니다. 

## 체크 포인트
- [x] annotation 설명 주석 달기 
- [x] 코드 컨벤션 지키기
- [x] 과도한 축약용어 사용하지 않기
- [x] 객체지향적인 코드 작성

2022-01-06 00:54 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +  @GetMapping("/{userSeq}/address")
@yeoonjae 
`address` 가 복수형이 되면 더 좋을 것 같습니다~ 
https://www.wordhippo.com/what-is/the-plural-of/address.html

2022-01-06 00:58 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  boolean selectAddressBySeq(Long addressSeq);
@yeoonjae 
boolean 응답타입이 의도하신걸까요~? 

(cc. @ypr821)

2022-01-06 01:02 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/Address.java
> +  private Long userSeq;
@yeoonjae 
아마 설계하신 DB 테이블과 연관이 있을 것 같은데요. 
Address 가 꼭 `userSeq`  를 알아야할까요? (DoorRush 의 프로젝트에서 Address 는 User 만 소유할 수 있도록 설계하는게 맞을까요?) Address 와 User의 결합을 없애고, 이 둘을 매핑하는 UserAddress 모델(테이블) 을 만드는 것은 어떤가요~? 
다시 한번 고민해주시면 좋을 것 같습니다. ㅎㅎ 

(cc. @ypr821)

2022-01-06 01:05 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/Address.java
> +  private String defaultYn;
@yeoonjae 
UserAddress 클래스에 defaultYn 이 있는데 중복되는 정보아닌가요~? 

(cc. @ypr821)

2022-01-06 01:06 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/UserAddressMapping.java
> +public class UserAddressMapping {
@yeoonjae 
`UserAddress` 네이밍이 조금 더 자연스러울 것 같습니다.

(cc. @ypr821)

2022-01-06 01:12 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/request/UserAddressRequest.java
> +  private Double spotY;
@yeoonjae 클라이언트로부터 위도와 경도 정보를 입력받을 수 있을까요~? 

(cc. @ypr821)

2022-01-06 01:13 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/response/UserAddressResponse.java
> +  private List<Address> addressList;
@yeoonjae 
address 에는 접근제어제가 붙지 않았습니다. 
address 와 addressList 의 차이는 무엇인가요~? 
그리고 복수형에 대해서는 ooo`s` or `oooList` 두개 중 하나라 프로젝트 전반적으로 일관성을 맞추어주시면 좋을 것 같습니다.

(cc. @ypr821)

2022-01-06 01:15 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  @Transactional(isolation = Isolation.READ_COMMITTED)
@yeoonjae 
요 메소드만 IsolationLevel 을 Read Commited 로 지정하신이유가 있으실까요~? 

(cc. @ypr821)

2022-01-06 01:16 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public UserAddressResponse registAddress(Long userSeq, UserAddressRequest userAddressRequest) {
@yeoonjae 
`register` 가 동사형이어서 수정해주심 좋을 것 같습니다. ㅎㅎ
그리고 코드가 너무 길어진다고 느껴진다면, 사용자 주소관련해서는 `UserAddressService` 로 분리하셔도 좋을 것 같습니다. 

(cc. @ypr821)

2022-01-06 01:18 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  private void registAddressMapping(Long userSeq, Address address) {
@yeoonjae 
메소드를 두개로 분리 하신 이유가 있을까요~? 

(cc. @ypr821)

2022-01-06 01:22 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    if (userMapper.isExistsDefaultAddress(userSeq) && address.getDefaultYn().equals("Y")) {
@yeoonjae 
"Y" 는 DB 에서 가져온 값일텐데요. 
DB 에서 Boolean 값을 YN 으로 관리하는것이 정책이라면,
매번 "Y" 인지 확인하기 위한 로직을 작성하기보다 도메인 클래스에서 이를 계산해서 boolean 으로 반환해주는 메소드를 만들어주면 더 좋을 것 같습니다. 그리고 "Y" 는 변하지 않는 값이니 상수로 관리하거나, enum 으로 관리해도 좋을 것 같습니다.


(cc. @ypr821)

2022-01-06 01:23 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    UserAddressMapping userAddressMapping = UserAddressMapping.builder().userSeq(userSeq)
@yeoonjae 
사소하지만 builder 사용 관련해서도 일관성있는 코드스타일로 작성해주시면 가독성에 더 좋습니다.
특이 케이스가 아니라면, 아래와 같은 형식으로 일관성있게 작성하는것은 어떨까요? 
```java
UserAddressMapping.builder()
  .userSeq(userSeq)
  .addressSeq(address.getAddressSeq())
  .defaultYn(address.getDefaultYn())
  .build();
```

(cc. @ypr821)

2022-01-06 01:25 UTC, f-lab-jd requested changes
@yeoonjae 
테스트코드까지 꼼꼼히 작성해주시고, 고생많으셨습니다! 👍 
리뷰드린 내용 한번 확인후 반영해주시면 감사하겠습니다.

2022-01-06 06:10 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/api/UserController.java
> +  @GetMapping("/{userSeq}/address")
넵 addresses로 수정하겠습니다.

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  boolean selectAddressBySeq(Long addressSeq);
@f-lab-jd 
넵 주소지 삭제 요청 시 해당 seq가 존재하는지 확인하기 위해 boolean 타입으로 의도했습니다.

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/domain/Address.java
> +  private Long userSeq;
@f-lab-jd 
주소지를 조회할 때 맵핑테이블과 조인을 하여 가져오는데에도 사용했어서 다른 테이블과 중복되는 정보가 들어갔습니다.
주소지 조회 시 사용할 객체를 만들어 사용하겠습니다!

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/domain/UserAddressMapping.java
> +public class UserAddressMapping {
넵 변경하겠습니다.

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dto/response/UserAddressResponse.java
> +  private List<Address> addressList;
@f-lab-jd 
앗 제가 접근제어자를 붙이는 것을 잊고 지나쳤습니다.. 
address와 addressList의 차이는 주소지 조회 시 List 형태로 받아와서 Controller 에서 응답 객체를 보낼 떄 `UserAddressResponse`로 일관성을 맞추기 위해서 사용했습니다.
넵 일관성 맞춰서 사용하도록 하겠습니다.

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  public UserAddressResponse registAddress(Long userSeq, UserAddressRequest userAddressRequest) {
@f-lab-jd
넵 따로 분리하겠습니다.

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    UserAddressMapping userAddressMapping = UserAddressMapping.builder().userSeq(userSeq)
넵 일관성있게 맟추겠습니다.

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  private void registAddressMapping(Long userSeq, Address address) {
@f-lab-jd
insert 하는 테이블이 달라서 따로 뺐습니다. 합치는 것이 좋을까요?

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +    if (userMapper.isExistsDefaultAddress(userSeq) && address.getDefaultYn().equals("Y")) {
@f-lab-jd 
넵 참고해서 수정하도록 하겠습니다.

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  @Transactional(isolation = Isolation.READ_COMMITTED)
@f-lab-jd 
커밋이 되기 전까지 다른 곳에서 읽을 수 없어야 한다고 생각해서 지정했습니다.

2022-01-06 07:06 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dto/request/UserAddressRequest.java
> +  private Double spotY;
@f-lab-jd 
아니요,, api를 통해서 받아와야 할 것 같습니다. 수정하겠습니다!

2022-01-06 08:36 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/domain/Address.java
> +  private String defaultYn;
@f-lab-jd 
https://github.com/f-lab-edu/DoorRush/pull/56#discussion_r779323118 와 같은 답변인데 이 부분은 주소지 조회 시 사용하는 객체를 만들어 사용하겠습니다.

2022-01-06 09:17 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dao/UserMapper.java
> +  boolean selectAddressBySeq(Long addressSeq);
@f-lab-jd 
다시보니 응답타입이 boolean이면 메소드명도 그에 맞게 수정이 필요할 것 같습니다!

2022-01-06 14:41 UTC, ypr821 reviewed
연재님 회원 주소 기능 구현하느라 정말 고생많으셨습니다!!!

2022-01-06 14:41 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  private void registAddressMapping(Long userSeq, Address address) {
@yeoonjae  @f-lab-jd 
궁금한점이 있습니다!
@Transactional 설정된 registAddress 메소드가 실행이 됐을때
내부적으로 private 메서드인 registAddressMapping을 호출하면 private 메서드도 @Transactional 어노테이션이 똑같이 적용되는 거죠??
AOP 관련 영상을 봤을때 헷깔리는 부분이 있어서 comment 남깁니다!
해당 영상에서는 private 메소드에만 AOP관련 어노테이션 설정을 해두고 프록시가 적용되는지 확인하는 거 같습니다...ㅜ

영상 링크는  https://www.youtube.com/watch?v=Hm0w_9ngDpM 
해당 부분은 9분19초 입니다.

2022-01-06 15:42 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  private void registAddressMapping(Long userSeq, Address address) {
@ypr821 
안녕하세요 푸름님! 저는 스프링 AOP 에 대해서 이해하기로는 `registAddressMapping` 이 호출이 되면 `registAddress` 메소드에서 시작된 트랜잭션(AOP)에 참여하는 것으로 이해했었습니다. 

프록시 객체의 `타깃 메소드A` 안에서 `타깃 메소드B`를 호출했을 때 `메소드B`에 적용되어있는 AOP가 적용되지 않는 것으로 알고있습니다. 

알고계실지도 모르겠지만 토비의 스프링 책에서 해당 내용에 관해서는 524페이지에 나와있습니다! 

혹시 제가 잘못이해하고 있는 점이 있다면 말씀 해주시면 감사하겠습니다.

2022-01-07 02:31 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  private void registAddressMapping(Long userSeq, Address address) {
@yeoonjae 님 책 페이지까지 알려주시고 정말 감사합니다!! 이해에 많은 도움이 됩니다 ㅎㅎㅎ감사합니다!!

2022-01-07 06:58 UTC, yeoonjae commented
@f-lab-jd @ypr821 안녕하세요 멘토님 푸름님 
우선 좌표사용을 위한 api 사용하는 부분을 제외하고 리뷰내용 반영해서 커밋하였습니다. 
api도 적용되는대로 반영하겠습니다!

2022-01-08 13:03 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  @Transactional(isolation = Isolation.READ_COMMITTED)
@yeoonjae 
어떤 경우에 쓰레드간 경합이 발생 할 수 있을까요~?
그리고 현재 서비스에서 이용하는 DB인 MySQL 의 기본 isolation level 은 무엇일까요~?
함께 고민해보시면 좋을 것 같습니다 ㅎㅎ (면접에 빈출되는 어렵고 중요한 내용입니다)
(cc. @ypr821)

2022-01-08 13:22 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  private void registAddressMapping(Long userSeq, Address address) {
@yeoonjae 
>  insert 하는 테이블이 달라서 따로 뺐습니다. 합치는 것이 좋을까요?

Application 의 로직이 DB 테이블의 형태에 의존하는것은 많은 사람들이 자주 범하는? 좋지 않은 습관이기도 합니다 ㅎㅎ 
Spring 개발자 관점에서 객체지향적으로 어떤 방식이 더 좋을지 한번 고민해보시면 좋을 것 같습니다.

@ypr821 
>  궁금한점이 있습니다!

아주 좋은 질문입니다 ㅎㅎ 면접에서도 어려운 질문으로 종종 나오는 주제인데요. 
연재님께서 깔끔하게 잘 답변해주셨네요 👍

2022-01-08 13:31 UTC, f-lab-jd approved these changes, later dismissed
고생하셨습니다. 👍 
리뷰 드린 내용 확인 후, 공감하는 내용들은 반영하시고 머징하시면 될 것 같습니다.

2022-01-08 13:31 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserAddressMapper.java
> +  boolean isExistsAddress(Long addressSeq);
👍

2022-01-08 13:31 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/domain/DefaultStatus.java
> +public enum DefaultStatus {
@yeoonjae 
`Default` 라는 네이밍이 조금 모호하게 느껴지기도하는데요. ㅎㅎ 
좀 더 직관적인 네이밍으로 `YnStatus`  로 네이밍해도 좋을 것 같네요.
그냥 의견이니 꼭 반영하지 않으셔도 됩니다. 

(cc. @ypr821)

2022-01-08 13:31 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/response/UserAddressResponse.java
> +    return userAddress.stream().map(UserAddressResponse::from).collect(Collectors.toList());
@yeoonjae 
`Builder` 와 마찬가지로 stream 의 chaining 코드도 일관성 있게 작성해주시면 더 좋을 것 같습니다. 
```java
return userAddress.stream()
        .map(UserAddressResponse::from)
        .collect(Collectors.toList());
```

(cc. @ypr821)

2022-01-08 13:31 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/response/UserAddressResponse.java
> +  public static boolean isDefault(DefaultStatus defaultStatus) {
@yeoonjae 
static 이어야하는 이유가 있나요~? 

(cc. @ypr821)

2022-01-08 13:31 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dto/response/UserAddressResponse.java
> +  public static List<UserAddressResponse> toUserAddressResponse(List<UserAddress> userAddress) {
@yeoonjae 
`to` 보다는 `from` 이 맞지 않을까요~? 

(cc. @ypr821)

2022-01-08 13:31 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/service/UserAddressService.java
> +        && UserAddressRequest.isDefault(userAddressRequest.getDefaultStatus())) {
@yeoonjae 
`userAddressMapper.isExistsDefaultAddress(userSeq) && isDefault(userAddressRequest.getDefaultStatus()` 를 가독성을 위해 하나의 private 메소드로 빼도 좋을 것 같습니다. 

(cc. @ypr821)

2022-01-09 16:08 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserService.java
> +  @Transactional(isolation = Isolation.READ_COMMITTED)
@f-lab-jd 
어떤 경우에 쓰레드간 경합이 발생 할 수 있을까요~?
**동일한 자원을 동시에 두 개 이상의 쓰레드에서 접근할 때 발생합니다.** 

MySQL 의 기본 isolation level 은 무엇일까요?
**MySQL의 기본 isolation level은 `REPEATABLE READ` 로 현재 트랜잭션이 적용되어있는 row를 다른 트랜잭션에서 수정할 수 없습니다.**

2022-01-09 16:08 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/domain/DefaultStatus.java
> +public enum DefaultStatus {
@f-lab-jd 
조금 더 적절한 이름인 YnStatus로 변경하는 것이 맞을 것 같습니다! 수정하겠습니다.

2022-01-09 16:08 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dto/response/UserAddressResponse.java
> +    return userAddress.stream().map(UserAddressResponse::from).collect(Collectors.toList());
@f-lab-jd 
넵 일관성있게 작성하겠습니다!!

2022-01-09 16:08 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dto/response/UserAddressResponse.java
> +  public static boolean isDefault(DefaultStatus defaultStatus) {
@f-lab-jd 
앗  다시 보니 static으로 선언하지 않아도 사용할 수 있을 것 같습니다. 수정하겠습니다.

2022-01-09 16:08 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/service/UserAddressService.java
> +        && UserAddressRequest.isDefault(userAddressRequest.getDefaultStatus())) {
@f-lab-jd 
넵 가독성있게 수정하겠습니다 !

2022-01-09 16:08 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/user/dto/response/UserAddressResponse.java
> +  public static List<UserAddressResponse> toUserAddressResponse(List<UserAddress> userAddress) {
넵 ! 수정하겠습니다 !

2022-01-10 05:02 UTC, ypr821 approved these changes
고생하셨습니다!!!!

2022-01-10 05:07 UTC, merged