[#60] 주문, 식당, 메뉴 테이블 생성 및 더미데이터 생성
f-lab-edu/DoorRush pull request #61
Opened 2022-01-14 16:17 UTC by yeoonjae

# [#60] 주문, 식당, 메뉴 테이블 생성 및 더미데이터 생성
- 테이블 생성
- 더미데이터 생성

## 리뷰 포인트 
- 기능 구현에 필요한 테이블 생성 및 더미데이터 생성하였습니다. 
- 배달 관련된 기능(라이더)은 주문테이블에서 제외하고 생성했습니다. 

## 체크 포인트
- [x] annotation 설명 주석 달기 
- [x] 코드 컨벤션 지키기
- [x] 과도한 축약용어 사용하지 않기
- [x] 객체지향적인 코드 작성

2022-01-15 11:44 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    DEFAULT_STATUS      VARCHAR(2)      NOT NULL,
@yeoonjae VARCHAR(`2`) 인 이유가 있나요~?  1이면 되지 않을까요? ㅎㅎ 
Y 혹은 N 값만 저장이 되는거라면 컬럼명에도 `_YN` post-fix 를 붙여주면 더 명시적일 것 같네요.
(cc. @ypr821)

2022-01-15 11:45 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    OWNER_SEQ               BIGINT              NOT NULL,
@yeoonjae `owner` 테이블이 별도 있나요~?

(cc. @ypr821)

2022-01-15 11:46 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    OPEN_STATUS             VARCHAR(2),
@yeoonjae  
https://github.com/f-lab-edu/DoorRush/pull/61/files#r785300034 와 같은 리뷰입니다.

(cc. @ypr821)

2022-01-15 11:47 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    NUMBER_OF_ORDERS        BIGINT DEFAULT 0,
@yeoonjae 
주문 횟수를 저장하는 이유는 무엇인가요~? 
주문 테이블의 데이터를 count 하면 되지 않을까요~!? 
별도로 컬럼이있을때 장/단점이 무엇일까요? ㅎㅎ 

(cc. @ypr821)

2022-01-15 11:48 UTC, f-lab-jd commented on src/main/resources/schema.sql
>      USER_SEQ     bigint NOT NULL AUTO_INCREMENT,
@yeoonjae 
모든 테이블에 공통적인 의견인데요. ㅎㅎ 
생성일/수정일도 저장이 필요하지 않을까요~? 

(cc. @ypr821)

(cc. @ypr821)

2022-01-15 11:48 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    INFO                    VARCHAR(500),
@yeoonjae INFO 라는 컬럼명은 좀 모호한 것 같습니다..ㅎㅎ 

(cc. @ypr821)

2022-01-15 11:49 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    ADDRESS             VARCHAR(100)   NOT NULL,
@yeoonjae 
ORDER 테이블에 ADDRESS_SEQ 가 아니라 ADDRESS 를 저장하는 이유는 무엇인가요~? 

(cc. @ypr821)

2022-01-15 11:50 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    ORDER_STATUS        INT            NOT NULL,
@yeoonjae 
ORDER_STATUS 에는 INT 형이 저장되나요~? 

(cc. @ypr821)

2022-01-15 11:51 UTC, f-lab-jd requested changes
@yeoonjae 
고생하셨습니다~! 리뷰드린 내용 한번 답변해보시고, 이해가 안되시는 부분이 있다면 말씀해주세요!

2022-01-16 09:39 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    DEFAULT_STATUS      VARCHAR(2)      NOT NULL,
@f-lab-jd 넵 변경하겠습니다 !

2022-01-16 09:39 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    OPEN_STATUS             VARCHAR(2),
@f-lab-jd 넵 변경하겠습니다 !

2022-01-16 09:39 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    INFO                    VARCHAR(500),
@f-lab-jd 좀 더 명시적인 컬럼명으로 변경하겠습니다.

2022-01-16 09:39 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    NUMBER_OF_ORDERS        BIGINT DEFAULT 0,
@f-lab-jd 
식당 조회 시 더 수월할 거라 생각이 들어서 컬럼으로 만들었습니다. 
컬럼으로 뺐을 때 **장점은 쿼리가 복잡하지 않고 복잡해질 경우 조회 속도가 빨라질 것 같습니다.** 
**단점은 매번 주문 시 식당테이블의 주문횟수를 +1해주어야 하여 비즈니스 로직이 복잡해질 것 같습니다.**

2022-01-16 09:39 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    ADDRESS             VARCHAR(100)   NOT NULL,
@f-lab-jd @ypr821 이 부분에 대해서 고민을 많이 했습니다! 
사용자는 배달지를 수시로 삭제 및 수정할 수 있는데 삭제된 배달지 ADDRESS_SEQ로 주문할 경우 주문이력을 볼 때 null 값으로 나올 것 같아서 ADDRESS로 받았습니다.

2022-01-16 09:39 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    ORDER_STATUS        INT            NOT NULL,
@f-lab-jd 
네 `PENDING(0)`, `CANCEL(1)`, `APPROVAL(2)` , 결제대기(3) 처럼 관리하려 했습니다!

2022-01-16 09:39 UTC, yeoonjae commented on src/main/resources/schema.sql
>      USER_SEQ     bigint NOT NULL AUTO_INCREMENT,
@f-lab-jd 
네 맞습니다. 필요할 것 같습니다. @ypr821 푸름님과 얘기 나눠보겠습니다!

2022-01-16 09:39 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    OWNER_SEQ               BIGINT              NOT NULL,
@f-lab-jd 아니요 따로 없습니다. 사장님 기능을 구현하지 않아서 임시로 넣었습니다!

2022-01-16 10:10 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    OWNER_SEQ               BIGINT              NOT NULL,
@yeoonjae 아하 그렇군요 ㅎㅎ 그렇다면 그대로 유지하셔도 좋을 것 같습니다.

2022-01-16 10:16 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    NUMBER_OF_ORDERS        BIGINT DEFAULT 0,
@yeoonjae 
잘 답변해주셨습니다. `정규화/반정규화` 키워드에 대해서도 한번 찾아보시면 더 좋을 것 같습니다. (cc. @ypr821)
말씀하신 두개의 트레이드오프가 생길텐데요. 성능/유지보수/확장성 모두 고려했을때 어떤 방법이 더 괜찮은 방법이라고 생각하시나요? ㅎㅎ 
(정답이 명확히 있는 내용이 아니니 편히 말씀해주세요)

2022-01-16 10:19 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    ADDRESS             VARCHAR(100)   NOT NULL,
@yeoonjae 
잘 생각하셨습니다 ㅎㅎ 식당정보(ex. 이름 ..) 도 마찬가지 아닐까요~?

2022-01-16 10:21 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    ORDER_STATUS        INT            NOT NULL,
@yeoonjae 
숫자로 저장했을때 어떤 장점이 있을까요? 그보다 직접 이름을 풀어서 저장하는게 더 낫지 않을까요? ㅎㅎ

2022-01-16 11:27 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    ORDER_STATUS        INT            NOT NULL,
@f-lab-jd 
int 형으로 저장한다면 데이터베이스 메모리를 덜 차지한다는 장점이 있습니다. 
명시적으로 이름으로 저장하겠습니다 ! ㅎㅎ

2022-01-16 11:27 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    ADDRESS             VARCHAR(100)   NOT NULL,
@f-lab-jd 
앗 네 맞습니다 식당정보도 이름으로 받아오도록 변경 하겠습니다!

2022-01-16 11:27 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    NUMBER_OF_ORDERS        BIGINT DEFAULT 0,
@f-lab-jd 
`정규화` : 중복을 최소화하도록 설계된 데이터베이스입니다. 
`반정규화` : 읽는 시간을 최적화하도록 설계된 데이터베이스로 개발 및 운영을 위해 의도적으로 정규화 원칙을 위배하는 행위입니다. 

읽기 성능 측면으로 볼 때는 join 비용을 줄여주어 비정규화가 괜찮은 방법인 것 같지만 중복되는 데이터만큼 메모리를 차지하고 갱신이 될 떄마다 다른 테이블도 갱신이 필요하여 쓰기 성능측면에서는 좋지 않을 것 같습니다. 
또한, 유지보수와 확장성 측면에서도 중복된 정보가 많을수록 확장성은 떨어지고 유지보수도 어려울 것 같아서 정규화가 괜찮은 방법일 것 같습니다. 

개발할 떄도 비정규화인 경우 고려해야할 사항이 더 생기는 것이니 정규화 방법이 더 괜찮은 방법이라 생각합니다.

2022-01-16 13:56 UTC, ypr821 commented on src/main/resources/schema.sql
> +    ADDRESS             VARCHAR(100)   NOT NULL,
@yeoonjae  @f-lab-jd  
궁금한 점이 있습니다!
식당 정보를 이름으로 가져올 경우 상호명이나 식당 이름이 같은 경우에는 문제가 생기지 않을까요??

2022-01-16 13:58 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    ADDRESS             VARCHAR(100)   NOT NULL,
@ypr821 
식당정보를 seq 값으로 받고 해당 seq값을 조회해서 식당이름을 넣는 방식으로 하려고 합니다!

2022-01-16 14:38 UTC, ypr821 commented on src/main/resources/schema.sql
> +    ADDRESS             VARCHAR(100)   NOT NULL,
@yeoonjae 
넵  insert 경우에는 문제가 없지만 select하는 경우가 궁금했습니다.
ORDER테이블에서 주문했던 식당에 대한 정보를 조회할때는 ORDER테이블에서 식당이름을 조회하고  해당 식당이름으로 RESTAURANT 테이블에서 조회가 이루어질 일은 없으려나요??  
아니면 식당에서 매출 분석을 위해 주문 수를 확인해야 하면 혹시 필요하지 않을까 했습니다 ㅎㅎ

2022-01-16 14:41 UTC, yeoonjae commented
@f-lab-jd @ypr821 
리뷰내용 반영하였습니다. 확인 부탁드립니다!
* ORDER_MENU 와 USER_ADDRESS_MAPPING 를 제외한 테이블에 생성일자와 수정일자 반영하였습니다. 
https://github.com/f-lab-edu/DoorRush/pull/61/commits/8576652a1ba0794d5385525f6afaa75c3435a1ed#

2022-01-16 14:54 UTC, yeoonjae commented on src/main/resources/schema.sql
> +    ADDRESS             VARCHAR(100)   NOT NULL,
@ypr821 
헉 그렇네요 생각못했습니다 ..ㅎㅎ
식당의 주문 건 수를 조회하기 위해선 seq 값도 필요할 것 같습니다.

2022-01-21 02:20 UTC, f-lab-jd approved these changes
고생하셨습니다 👍

2022-01-21 05:17 UTC, merged