[#24] 주문 insert 기능 구현
f-lab-edu/DoorRush pull request #64
Opened 2022-01-18 18:05 UTC by yeoonjae

# [#24] 주문 insert 기능 구현
- 주문 insert 기능 구현
- 주문 메뉴 insert 기능 구현

## 리뷰 포인트 
- schema.sql, data,sql 과 카카오 API 적용은 임시로 적용시켰습니다. (다른 PR 에서 리뷰 진행)
- Order, OrderMenu와 관련된 기능만 리뷰 부탁드립니다. 
- restaurant 관련 기능은 식당 이름을 받아오기 위해 구현한 것입니다. 

## 체크 포인트
- [x] annotation 설명 주석 달기 
- [x] 코드 컨벤션 지키기
- [x] 과도한 축약용어 사용하지 않기
- [x] 객체지향적인 코드 작성

2022-01-22 14:45 UTC, f-lab-jd requested changes
@yeoonjae 
고생하셨습니다! 리뷰드린 내용 한번 확인해보시고, 이해 안되시는 부분이 있다면 말씀해주세요.

2022-01-22 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/api/OrderController.java
> +  @GetMapping("checkPrice")
@yeoonjae 
rest api 에서 url 은 camelCase보다는 dash-case 를 더 많이 사용하는데요. 
왜 그럴지 혹시 짐작해보시겠어요~?

그리고 현재 API 의 목적은 무엇인가요? 
`checkPrice` 라는 네이밍을 보았을때에는 주문을 위한 금액을 검증하는 용도로 짐작이 됩니다. 
Price 만 꼭 응답해야하는 이유가 혹시 있을까요~?

2022-01-22 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/dao/OrderMapper.java
> +  Long selectTotalPrice(List<Menu> menus);
@yeoonjae 
`ByMenus` 가 들어가면 더 일관적일 것 같습니다.
null 일 경우를 대비해 Optional 로 감싸는게 더 좋지않을까요~?

2022-01-22 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/domain/Order.java
> +  private String orderTime;
@yeoonjae String 인 이유가 있나요~?

2022-01-22 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/dto/request/Menu.java
> +  public OrderMenu toEntity(Long orderSeq){
@yeoonjae Menu 클래스는 Entity 가 아닌가요? 
Menu 클래스에서 toEntity 호출결과 OrderMenu 클래스가 된다는것이 좀 어색합니다 ㅎㅎ 
Menu 가 Dto 클래스라면 네이밍 수정이 필요할 것 같네요.

2022-01-22 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/dto/request/Menu.java
> +  private int count;
@yeoonjae Menu 클래스에는 count 프로퍼티만 있으면 되나요?
그리고 Menu 클래스에서 count 프로퍼티는 메뉴의 갯수를 의미하는것이 맞나요~?

2022-01-22 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/service/OrderService.java
> +    addOrderMenu(orderRequest.getMenus(), order.getOrderSeq());
@yeoonjae 
insertOrder 는 성공했지만, insertOrderMenu 가 실패한 경우 insert 된 order 데이터는 어떻게 되어야할까요?

2022-01-22 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/service/OrderService.java
> +    menus.forEach(menu -> orderMenus.add(menu.toEntity(orderSeq)));
@yeoonjae 
menus 가 비어있는 경우는 NPE 가 나지 않을까요~?

2022-01-22 14:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/global/exception/GlobalExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(BasicResponse.fail(e.getMessage()));
@yeoonjae GlobalExceptionHandler 에서 로그를 남기는게 더 좋을 것 같습니다.

2022-01-22 15:34 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/global/exception/GlobalExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(BasicResponse.fail(e.getMessage()));
@f-lab-jd 넵 로그 남기도록 하겠습니다.

2022-01-22 15:34 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/dao/OrderMapper.java
> +  Long selectTotalPrice(List<Menu> menus);
넵 null일 경우를 생각 못했습니다.감사합니다. Optional로 감싸겠습니다!

2022-01-22 15:34 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/domain/Order.java
> +  private String orderTime;
앗 시간이니 LocalDateTime으로 사용하겠습니다!

2022-01-22 15:34 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/dto/request/Menu.java
> +  public OrderMenu toEntity(Long orderSeq){
@f-lab-jd 
넵 어색하지 않도록 MenuDto로 변경하도록 하겠습니다.

2022-01-22 15:34 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/service/OrderService.java
> +    menus.forEach(menu -> orderMenus.add(menu.toEntity(orderSeq)));
@f-lab-jd 
넵 OrderRequest 에서 @NotNull 로 체크했는데 List니 @NotEmpty로 변경이 필요할 것 같습니다. 혹시 모르니 null체크하는 로직도 추가하도록 하겠습니다.

2022-01-22 15:34 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/service/OrderService.java
> +    addOrderMenu(orderRequest.getMenus(), order.getOrderSeq());
@f-lab-jd 
Transaction 처리를 하여 insertOrder 역시 롤백을 하고 예외를 던져줘야 할 것 같습니다.

2022-01-22 15:34 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/api/OrderController.java
> +  @GetMapping("checkPrice")
@f-lab-jd 
REST API 설계에서 dash-case 가 더 직관적으로 파악이 가능해서 사용하는 것 같습니다. 

현재 API의 목적은 주문 전 메뉴의 정보를 받아 합계금액을 조회하는 API입니다. 처음 전체금액에 대한 정보가 없으니 이를 응답해야겠다고 생각했습니다. 조금 더 생각해보니 메뉴의 정보도 같이 응답하면 좋을 것 같습니다.

2022-01-22 15:34 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/dto/request/Menu.java
> +  private int count;
@f-lab-jd 
넵 Menu 클래스가 네이밍을 도메인처럼 잘못 지은 것 같습니다. 클라이언트가 선택한 메뉴명과 선택한 메뉴의 개수를 입력받는 DTO로 쓰여서 개수만 필요하다고 생각했습니다!

2022-01-26 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/domain/Order.java
> +  private Timestamp orderTime;
@yeoonjae LocalTime 이 아닌 Timestamp 를 사용하신 이유가 있으신가요~?

2022-01-26 13:38 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/dto/response/OrderMenuCart.java
> +public class OrderMenuCart {
@yeoonjae OrderMenuCart 클래스는 역할이 무엇인가요~?

2022-01-26 13:45 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/service/OrderService.java
> +    Long totalPrice = orderMenuCarts.stream().map(OrderMenuCart::getMenuSumPrice)
@yeoonjae 
아래와 같이 메소드 레퍼런스를 사용해서 더 간결히 표현하실 수 있습니다.
stream도 builder 와 같이 일관성있는 포맷팅으로 작성하시면 더 좋을 것 같습니다.
``` java
Long totalPrice = orderMenuCarts.stream()
        .map(OrderMenuCart::getMenuSumPrice)
        .mapToLong(Math::toIntExact)
        .sum();
```

2022-01-26 15:50 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/domain/Order.java
> +  private Timestamp orderTime;
@f-lab-jd 
주문 시간으로 변수명을 짓긴 했지만 주문한 날짜도 같이 나와야 할 것 같아서 TimeStamp를 사용했습니다!

2022-01-26 15:53 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/dto/response/OrderMenuCart.java
> +public class OrderMenuCart {
@f-lab-jd 
Controller 에서 check-price 요청이 들어왔을 때 응답으로 총 가격뿐만 아니라 주문한 메뉴의 정보와 개수, 금액도 나와야한다고 생각해서 만든 클래스입니다!

2022-01-26 15:54 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/service/OrderService.java
> +    Long totalPrice = orderMenuCarts.stream().map(OrderMenuCart::getMenuSumPrice)
@f-lab-jd 
넵넵 가독성 좋은 코드를 위해선 Stream에 대해 더 학습이 필요할 것 같습니다!! 감사합니다!!

2022-01-28 00:33 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/domain/Order.java
> +  private Timestamp orderTime;
@yeoonjae 
그러면 네이밍을 변경 후에 Java 8 부터 제공하는 날짜/시간이 포함된  타입을 사용하는건 어떨까요? ㅎㅎ

2022-01-28 00:34 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/order/dto/response/OrderMenuCart.java
> +public class OrderMenuCart {
@yeoonjae 
장바구니 기능이 따로 있나요~? 
장바구니 도메인이 없는데 Cart 라는 네이밍이 등장해서 조금 어색합니다. ㅎㅎ

2022-01-30 15:04 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/dto/response/OrderMenuCart.java
> +public class OrderMenuCart {
@f-lab-jd 장바구니 기능은 따로 없습니다..!! 네이밍을 좀 더 생각해보겠습니다 !

2022-01-30 15:04 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/order/domain/Order.java
> +  private Timestamp orderTime;
@f-lab-jd 맨 처음 LocalDateTime을 사용했었는데 바인딩 에러가 나서 TimeStamp로 변경했었습니다,,!! 다시 한 번 적용해보겠습니다.

2022-02-02 04:27 UTC, f-lab-jd approved these changes

2022-02-02 04:46 UTC, merged