[#66],[#65] 식당insert기능, 로그인체크기능 추가
f-lab-edu/DoorRush pull request #68
Opened 2022-01-27 03:02 UTC by ypr821

# 구현내용 요약
- [#66 ] 식당 insert 기능 추가
- [#65 ] 로그인 체크 AOP 추가

## 리뷰 포인트 
- AOP 테스트 코드 작성에 피드백이 필요합니다.
- controller에 요청이 들어올때 Request body의 String 데이터를 enum클래스로 바로 바인딩할 수 있는 방법을 고민중입니다.

## 체크 포인트
- [ ] annotation 설명 주석 달기 
- [X] 코드 컨벤션 지키기
- [X] 과도한 축약용어 사용하지 않기
- [X] 객체지향적인 코드 작성

2022-01-27 05:48 UTC, yeoonjae commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-aop:2.6.2'
@ypr821 푸름님!
버전은 명시하지 않아도 될 것 같습니다!
https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/dependency-versions.html#dependency-versions

2022-01-27 06:26 UTC, yeoonjae reviewed
정말 고생많으셨습니다 !! 👍

2022-01-27 06:26 UTC, yeoonjae commented on src/main/resources/mybatis/mapper/RestaurantMapper.xml
> +      AND INTRODUCTION = #{introduction}
@ypr821 
조건문에 INTRODUCTION 가 들어있으면 전체 문자열을 비교하는 것이니 성능상 안좋지 않을까 생각이 듭니다.

2022-01-27 06:26 UTC, yeoonjae commented on src/main/java/com/flab/doorrush/domain/restaurant/restaurantEnum/RestaurantCategory.java
> +  @JsonCreator
@ypr821 
푸름님 질문이 있습니다. 여기서 `@JsonCreator` 와 `@JsonProperty("category")`을 사용하신 이유가 있으신가요 ? ENUM 클래스에서만 사용하셔서 다른 이유가 있는지 궁금합니다.

2022-01-28 09:07 UTC, ypr821 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-aop:2.6.2'
피드백 감사합니다 연재님 수정하겠습니다 ㅎㅎ

2022-01-28 09:11 UTC, ypr821 commented on src/main/resources/mybatis/mapper/RestaurantMapper.xml
> +      AND INTRODUCTION = #{introduction}
@yeoonjae  넵! 생각해 보니 INTRODUCTION을 꼭 비교하지 않아도 될 거 같네요! 
아 연재님 MINIMUM_ORDER_AMOUNT도 뺄가 하는데 어떻게 생각하세요??
select 도중에 주문 수가 늘어날 경우 fail 날 수도 있지 않을 까 하는 의문이 들었습니다

2022-01-28 09:46 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/restaurantEnum/RestaurantCategory.java
> +  @JsonCreator
@yeoonjae 
Json body로 들어오는 값을 enum 클래스로 매핑할 수 있는 방법을 고민하고 있습니다.!! 이부분은 제가 좀 더 공부하고 수정해서 다시 공유드려도될까요?? 아직 고민중인코드인데 같이 올라갔네요 !!

2022-01-29 08:27 UTC, f-lab-jd requested changes
@ypr821 고생하셨습니다~ 이해가 안되시는 리뷰내용이 있다면 말씀해주세요!

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/authentication/aspect/CheckLoginAspect.java
> +    if (currentId == null || currentId.equals("null")) {
@ypr821 
currentId 가 "null" 이라는 값이 할당 되는 경우도 있나요~? 
StringUtils 를 활용하여 String 이 비어있는지 체크하는것은 어떨까요?

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/api/RestaurantController.java
> +    addRestaurantRequest.setOwnerSeq(ownerSeq);
@ypr821 request DTO 는 불변객체여야 할 것 같습니다. 
setter 는 막아두고, addRestaurant 메소드에 request DTO 와 seq 를 넘기는것은 어떨까요?

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/dao/RestaurantMapper.java
> +  Long selectRestaurantSeq(Restaurant restaurant);
@ypr821 restaurantSeq 를 restaurant 객체로 조회는 어떤 경우하나요?

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/domain/Restaurant.java
> +  private char openYN;
@ypr821 char 타입이면 Y와 N 말고 다른 값도 들어올 수 있지 않을까요? 
기존에 만들어 두셨던 YnStatus 를 잘 활용해보는건 어떨까요? (YnStatus 는 user 도메인에 정의되어있기떄문에 고민해보심 좋을 것 같습니다)

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/dto/request/AddRestaurantRequest.java
> +  private String category;
@ypr821 category 는 enum 으로 표현할 수 있을까요?

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/dto/request/AddRestaurantRequest.java
> +        .minimumOrderAmount(0L)
@ypr821 minimumOrderAmount 는 항상 0 인가요?

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/exception/AddRestaurantException.java
> +    RuntimeException {
@ypr821 포맷터가 개행한걸까요~?

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/service/RestaurantService.java
> +    } catch (Exception e) {
@ypr821 
try ~ catch 로 감싼 이유가 있으신가요? 
try ~ catch 로 감싸는 기준은 무엇이고, 작성해주신것처럼 예외의 가장 상위 클래스인 `Exception` 을 catch 구문에 넣었을때 우려할 수 있는 점과 단점은 무엇일까요?

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/user/dao/UserAddressMapper.java
> +  Long selectAddressSeq(Address address);
@ypr821 
RestaurantMapper 코드에 드렸던 질문과 같은 내용입니다.

2022-01-29 08:27 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/service/RestaurantService.java
> +      Long addressSeq = userAddressMapper.selectAddressSeq(address);
@ypr821 useGeneratedKeys 설정을 하였는데 select 문이 꼭 필요한가요?

2022-02-05 15:46 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/dto/request/AddRestaurantRequest.java
> +        .minimumOrderAmount(0L)
@f-lab-jd 네! 식당이 처음 등록되기 때문에 주문 수를 0으로 셋팅했습니다!

2022-02-05 15:47 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/exception/AddRestaurantException.java
> +    RuntimeException {
@f-lab-jd  수정하겠습니다 ㅎㅎ

2022-02-06 08:22 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/dto/request/AddRestaurantRequest.java
> +        .minimumOrderAmount(0L)
@ypr821 그렇다면 AddRestaurantRequest 클래스에 `minimumOrderAmount` 프로퍼티는 불필요해보입니다.

2022-02-06 17:02 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/api/RestaurantController.java
> +    addRestaurantRequest.setOwnerSeq(ownerSeq);
@f-lab-jd  
넵 그렇게 해야겠어요 
수정하겠습니다!!!

2022-02-06 18:13 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/dao/RestaurantMapper.java
> +  Long selectRestaurantSeq(Restaurant restaurant);
selectRestaurantSeq 메서드는 테스트를 위해서 만든 메소드입니다.. 
addRestaurantSuccessTest 에서 Service의 addRestaurant() 메소드 실행후 저장을 확인하기 위해서 만들었습니다.

2022-02-06 18:17 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/domain/Restaurant.java
> +  private char openYN;
@f-lab-jd 
네 제가 코드를 작성할때는 해당 클래스가 없었습니다. 
그래서 연재님께서 머지하신 후에 develop branch에서 역머지하고 적용했습니다!
다만,  YnStatus 는 여러 도메인에서 사용할 수 있을 거 같습니다.  global 패키지하위로 옮기면 어떨까요??

2022-02-06 18:19 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/dto/request/AddRestaurantRequest.java
> +        .minimumOrderAmount(0L)
@f-lab-jd 
멘토님 제가 착각을 했습니다 !! `minimumOrderAmount `는 최소 주문 금액이였습니다. 
다시 수정해보겠습니다 ㅎㅎㅎ

2022-02-06 18:28 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/dto/request/AddRestaurantRequest.java
> +  private String category;
@f-lab-jd 
제가 요부분이 고민이었습니다 
클라이언트 요청 body부분에서 바로 enum 클래스 타입으로 매핑해서 받아 올 수 있을 거 같습니다. 
대신 변수명이 조금이라도 틀리면 에러가 발생하는 걸로 알고 있습니다.

2022-02-06 18:31 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/service/RestaurantService.java
> +    } catch (Exception e) {
@f-lab-jd 
try문 안에서 발생하는 모든 exception을 다 받아서 AddRestaurantException으로 던져주려고 했습니다.
원인이 되는 exception을 같이 넘겨주긴 합니다......
그렇지만 조금 친절하지 않은 예외 처리 인 거 같습니다.

2022-02-06 19:04 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/service/RestaurantService.java
> +    } catch (Exception e) {
try ~ catch 로 감싸는 기준은 무엇일까요?

예외를 같이 처리해야 하거나 단계별로 처리 해야 할 때
예외가 발생할 수 있는 부분을 try로 감싸주고 catch로 예외를 처리해야합니다.


<br>

작성해주신것처럼 예외의 가장 상위 클래스인 Exception 을 catch 구문에 넣었을때 우려할 수 있는 점과 단점은 무엇일까요?

구체적이지 않기 때문에 광범위한 예외처리가 될 수 있다는 것이 단점인 거 같습니다.
해당 try문 안에서 발생할 수 있는 예외를 예상해보고 테스트로 확인하면서 예외 처리 로직을 구체화 해야 좋을 거 같습니다.

2022-02-07 05:36 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/service/RestaurantService.java
> +      Long addressSeq = userAddressMapper.selectAddressSeq(address);
@f-lab-jd  
네 필요합니다 ! ADDRESS 테이블에 주소를 입력하고 입력된 주소의 seq를 가지고와서 
RESTAURANT테이블에 insert할때 ADDRESS_SEQ 컬럼의 값으로 담아주기 위해서는 필요하다고 생각합니다.

2022-02-07 06:15 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/authentication/aspect/CheckLoginAspect.java
> +    if (currentId == null || currentId.equals("null")) {
현재는 "null" 값이 할당되는 경우가 없습니다. 삭제하겠습니다!
StringUtils  클래스에서 isEmpty는 Deprecated 상태여서 
공식문서를 보고 hasLength로 null 체크 할 수 있다고 해서 적용해서 수정했습니다.

2022-02-07 07:00 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/order/domain/Order.java
>    private Long amount;
@f-lab-jd  
역머지하고 나서 커밋하는데 Order 부분이 왜 같이 올라온건지 모르겠습니다.

2022-02-08 14:53 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/dao/RestaurantMapper.java
> +  Long selectRestaurantSeq(Restaurant restaurant);
@ypr821 
테스트시에 꼭 필요한 메소드인가요? 다른 방법은 없을까요~? 
실제 비즈니스로직에 사용되지 않고, 테스트에서만 사용되는 메소드를 만드는것은 지양하는것이 좋습니다.

2022-02-08 14:54 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/dto/request/AddRestaurantRequest.java
> +  private String category;
@ypr821 넵 맞습니다. 말씀하신 내용이 enum 을 사용할때 얻을 수 있는 장점이기도 합니다 ㅎㅎ

2022-02-08 15:03 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/service/RestaurantService.java
> +    } catch (Exception e) {
@ypr821 넵 답변 잘 해주셨습니다. 예외는 구체적으로 정의해서 처리할 수록 좋습니다!

2022-02-08 15:05 UTC, f-lab-jd commented on src/main/java/com/flab/doorrush/domain/restaurant/service/RestaurantService.java
> +      Long addressSeq = userAddressMapper.selectAddressSeq(address);
@ypr821 `insertAddress` 에 매핑된 mybatis 설정에 useGeneratedKeys 설정이 있어서 seq 값을 가져올 수 있지 않나요~?

2022-02-08 15:07 UTC, f-lab-jd approved these changes
고생하셨습니다 👍

2022-02-09 03:19 UTC, merged

2022-02-09 08:07 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/dao/RestaurantMapper.java
> +  Long selectRestaurantSeq(Restaurant restaurant);
@f-lab-jd 
넵 멘토님 !! 지양하겠습니다.

멘토님 Read 기능에 사용할 메서드를 생성하고 테스트에 사용하는 방법은 어떨까요??
그리고 insert한 값을 test하는 방법으로 select하여 값을 비교하는 방법 말고 다른 방법이 있나요???

2022-02-09 08:09 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/user/dao/UserAddressMapper.java
> +  Long selectAddressSeq(Address address);
@f-lab-jd  selectAddressSeq 메소드는 RestaurantService의 addRestaurant메소드에서 사용하고 있습니다.

2022-02-09 08:51 UTC, ypr821 commented on src/main/java/com/flab/doorrush/domain/restaurant/service/RestaurantService.java
> +      Long addressSeq = userAddressMapper.selectAddressSeq(address);
아하....   감사합니다.ㅎㅎㅎㅎ